### ISSUE TITLE
탭 컴포넌트 개수가 많아질 경우, 페이징 또는 별도 처리

### ISSUE THREAD

**Issue by seogi1004** [juijs/jui#194]
요구사항이 있음...

**Comment by easylogic** [comment]
보통 이런 경우는 탭 레이어에  양쪽 화살표를 뛰워서 특정 간격만큼 옮기는 것을 많이 사용함.

**Comment by seogi1004** [comment]
ㅇ,.ㅇ 맞음... 디자인 이슈도 있어서 요하한테 물어봐야지
