### ISSUE TITLE
[문서] 영문 메뉴얼 API -> 코드 주석으로 변경

### ISSUE THREAD

**Issue by seogi1004** [juijs/jui#215]
이번주까지 일요일까지 합시다.
진호형은 chart 관련만 다 옮겨주시고, 나머지는 내가 다하겠음...

**Comment by seogi1004** [comment]
여기 API에 있는것만 해주시면 되오!!!

http://seogi1004.github.io/jui/en/index.html#script/chart
http://seogi1004.github.io/jui/en/index.html#script/realtime

**Comment by easylogic** [comment]
이거 얼마나 더 해야함 ?
