### ISSUE TITLE
cylinder3d 버그 

### ISSUE THREAD

**Issue by easylogic** [juijs/jui#222]
grid3d 에서 depth 를 100 으로 줬을 때 정상적으로 나오지 않음 

cylinder3d.html 샘플가지고 테스트 해봄

**Comment by easylogic** [comment]
cylinder3d 는 다시 설계해야할 듯 

![image](https://cloud.githubusercontent.com/assets/591983/6563330/ad648550-c6e3-11e4-995e-854f6ed450be.png)

이미지를 보면 알겠지만 depth 에 따른 cylinder 가 전혀 변화가 없음 

rect 는 depth 따라 z 축이 늘어나는데 cylinder 는 그러지 않음. 

아님 내가 이미지를 잘 못 이해하고 있을 수 있음.

**Comment by seogi1004** [comment]
나도 알고 있는 버그임... 이게 depth와 degree에 맞게 적절한 모양으로 보여줘야 하는데...
현재는 원 사이즈만 맞추는 수준임... 차후에 개선할 문제임... ㅠㅠ
