### ISSUE TITLE
color.darken, lighten 에서 gradient 패턴 추가하기

### ISSUE THREAD

**Issue by easylogic** [juijs/jui#230]
3d 차트에서 팔요함. 

색상이 안맞네. 

gradient 패턴이 이상해짐

**Comment by seogi1004** [comment]
패턴도 마찬가지이긔~~ 고려 좀 해주셈!

**Comment by easylogic** [comment]
패턴에는 darken, lighten 을 애초에 적용못함.. 

그 놈은 색상이 아니여.

**Comment by easylogic** [comment]
적용할려면 모든 element 의 색상 요소를 다시 다 파악해서 다 풀어헤쳐야함.

**Comment by seogi1004** [comment]
이거 클로즈합니다!

**Comment by seogi1004** [comment]
ㅈㅅㅈㅅ
