### ISSUE TITLE
[Scatter 크기조절] 특정 데이터에 한해 scatter size 조절 혹은 bold표기

### ISSUE THREAD

**Issue by choisee** [juijs/jui#260]
예를 들어 data= [ { sales : 2, profit : 6, dept : 7 }, { sales : 5, profit : 6, dept : 2 }];
중 sales=5 인 scatter 에 대해서만 brush size를 증가(9->13)시킬수있나요? brush가 안된다면 하나의 data에 한해서 scatter 점 size를 키우고 싶습니다. size 조절이 안된다면 굵기를 조절가능하게 해주시면 감사하겠습니다.

**Comment by easylogic** [comment]
현재는 특정 데이타에 한해서 설정할 수 있는 기능이 없습니다. 

다만 brush 를 그릴 때 sales 와 profit 을 구분해서 그리고 싶으시면 
아래 처럼 필드별로 scatter 를 그리실 수는 있습니다. 

```javascript
brush : [
   { type : 'scatter', size : 8, target : 'sales' },
   { type : 'scatter', size : 3, target : 'profit' }  
]
```

특정 데이타에 한해서 size 나 다른 속성이 바뀌는건 기획이 되면 기능을 추가 해보도록 하겠습니다.

**Comment by easylogic** [comment]
size 도 callback 형태로 지정이 되어야 할 듯 하네요.
