### ISSUE TITLE
테이블에서 칼럼의 폭을 자유롭게 고정하는 방법을 알고 싶어요

### ISSUE THREAD

**Issue by socrates7** [juijs/jui#262]
윈도우 탐색기를 한번 만들어보려고 하는데 여기서 제공되는 테이블의 칼럼은 100%로 되어 있어 유저가 고정시킬수 없네요.
PC의 윈도우 탐색기를 보면 오른쪽의 파일 리스트에서 속성정보에 대한 칼럼들은 고정된 폭을 같습니다. 윈도우의 전체 크기가 변해도 파일의 속성정보를 표시하는 폭은 변동이 없는거죠. 
그런 기능이 있으면 좋겠는데요.

**Comment by seogi1004** [comment]
많은 컬럼이있을 경우 대응할 수 있는 테이블 컴포넌트를 기획 중입니다. ^^
