### ISSUE TITLE
[JUI] Scatter Chart: 값 표기가 되게끔, 그리고 각 연결점이 서로 선으로 연결되도록 개발 요청 가능할까요?

### ISSUE THREAD

**Issue by jinammin** [juijs/jui#276]
Scatter Chart: 값 표기가 되게끔, 그리고 각 연결점이 서로 선으로 연결되도록 개발 요청 가능할까요?

현재 Scatter Chart를 이용하여 A라는 항목의 Max, Average, Min을 표현하고, B라는 항목도 마찬가지로 표현하고 있습니다.
다만, 화면상에 값 표기가 되지 않기 때문에 한 번에 값이 이해되지 않고, 인쇄용으로 사용하기에도 제약이 따르는 상태입니다.

이에 따라, A라는 항목의 Max, Average, Min을 구할 때 각각의 점수가 화면상에 표시되게끔 "display = all" 등의 옵션을 개발해주시면 감사하겠습니다. 또한, Max, Average, Min이 서로가 연관되어 있음을 나타내기 위해 선으로 표시를 할 수 있으면 보다 유용하게 활용할 수 있을 것 같습니다.

예시)
Max: 70
    l
    l
    l
Average: 43
    l
    l
    l
Min: 10

**Comment by easylogic** [comment]
@jinammin  질문하신 부분 현재 데이타 구성을 어떻게 하셨는지 물어봐도 될까요?

**Comment by jinammin** [comment]
domain에는 'Korea', 'USA' 이라고 넣었고,
data에는 { min: 0.333333, avg: 9.4666666633553, max: 79 }, { min: 36.6667, avg: 39.8333339691162, max: 43 } 라고 넣었습니다.

**Comment by easylogic** [comment]
korea , usa 가 x 축으로 나오고 

y 축에 min, avg, max 가  scatter 형태로 패스로 연결 되면 되는건가요?  

이런 형태면 현재 차트에서 지원 되는 부분이 없습니다. 

새로 만들어야 할 것 같아요 ~

**Comment by jinammin** [comment]
네 말씀하신게 맞습니다. Y축인 min, avg, max가 서로 l 자 형태의 패스로 연결되기를 바라는거죠. 이렇게 되면 X축의 개수가 많아지더라도 혼동이 줄고 확실하게 구분이 될 수 있다는 장점이 있을 것으로 생각합니다.
새로 만든다고 하시면, 곧 개발되어 사용할 수 있을 것으로 생각해도 되는것인지요? ^^

**Comment by easylogic** [comment]
네, 따로 이슈로 등록해야할 것 같네요. 

어떤 차트 쓰시는건가요?

**Comment by seogi1004** [comment]
일단 scatter 브러쉬의 display 옵션에 all을 추가하였습니다.
(bar와 column도 동일)

**Comment by jinammin** [comment]
"최고점과 최저점을 연결하는 선"에 대한 예시 이미지가 있어서 첨부합니다.
제가 만든 자료가 있긴한데, 이미지 업로드가 불가능해서 최대한 비슷한걸로 링크 주소 남깁니다.
http://blogfiles.naver.net/data29/2007/10/9/209/box_plot_016_sumini15.jpg
해당 그림에서 가운데 박스가 아니라, 최고점부터 최저점까지 연결되는 선을 확인하시면 됩니다.

**Comment by easylogic** [comment]
http://seogi1004.github.io/jui/res/chartplay/index.html#candlestick.js

주식 차트랑 비슷하군요 ~ 

저 브러쉬를 조금 변형하면 비슷하게 만들 수도 있을 것 같네요.
