### ISSUE TITLE
[JUI] Basic Column Chart와 Active Stacked Bar Chart가 샘플 코드로 구현이 안되는 문제

### ISSUE THREAD

**Issue by jinammin** [juijs/jui#277]
Basic Column Chart와 Active Stacked Bar Chart가 샘플 코드로 구현이 안되는 문제가 있습니다.

Line Chart나 Pie Chart 등 다수의 Chart는 샘플 데이터를 이용하여 구현이 가능했으나, 위의 2 Chart는 샘플 코드로 구현이 되지 않습니다. 아무래도 제가 JUI를 사용함에 있어 미숙한 면이 있기 때문으로 보입니다.

그래서 부탁드리건데, 해당 샘플 코드를 확인해실 수 있는지요? 정상적으로 동작한다면 댓글에 제가 테스트 해볼 수 있도록 동작 가능한 샘플 코드를 적어주시면 감사드리겠습니다.

**Comment by easylogic** [comment]
사용하신 샘플 코드 좀 올려주세요.  그럼 좀 더 빠른 확인이 가능 할 것 같습니다. 

현재 jui 소스 안에 있는 sample 이랑  Chart Play 에 있는 코드랑 구조가 좀 달라서요.

**Comment by jinammin** [comment]
StackBar의 경우 sample 폴더 내에 있는 코드를 이용하였습니다. 제가 사용한 코드는 다음과 같으니 확인 바랍니다.

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="./jui-develop/jui-develop/jui.css" />
	<script src="./jui-develop/jui-develop/lib/jquery-1.8.0.min.js"></script>
	<script src="./jui-develop/jui-develop/jui.js"></script>
</head>
<body class="jui">

	<script id="tpl_tooltip" type="text/template">
		<div class="tooltip tooltip-top tooltip-black">
			<div class="anchor"></div>
			<div class="message"><!= obj.dataKey !>: <!= obj.data[obj.dataKey] !></div>
		</div>
	</script>


<script id="script_code">
var chart = jui.include("chart.builder");
var activeIndex = 0,
    data = [
        { quarter : "1Q", samsung : 50, lg : 35, sony: 10 },
        { quarter : "2Q", samsung : 20, lg : 30, sony: 5 },
        { quarter : "3Q", samsung : 20, lg : 5, sony: 10 },
        { quarter : "4Q", samsung : 30, lg : 25, sony: 15 }
    ];

chart("#chart-content", {
    series : {
        samsung : {
            color : 0,
            text : "Samsung"
        },
        lg : {
            color : 1,
            text : "LG"
        },
        sony : {
            color : 2,
            text : "SONY"
        }
    },
    axis : {
        x : {
            type : "range",
            domain : function(data) {
                return data.samsung + data.lg + data.sony;
            },
            line : true,
            orient: "top"
        },
        y : {
            type : "block",
            domain : "quarter",
            line : true
        },
        data : data
    },
    brush : {
        type : "stackbar",
        active : activeIndex,
        activeEvent : "click",
        target : [ "samsung", "lg", "sony" ]
    },
    widget : [{
        type : "title",
        text : "Bar Sample",
        orient : "bottom",
        align : "end"
    }, {
        type : "legend",
        filter : true
    }],
    event : {
        "mousedown" : function(d) {
            activeIndex = d.dataIndex;
        },
        "legend.filter" : function(target) {
            this.updateBrush(0, { active: activeIndex });
        }
    }
});

	})
</script>


</body>
</html>

**Comment by jinammin** [comment]
StackBar의 경우 sample 폴더 내에 있는 코드를 이용하였습니다. 제가 사용한 코드는 다음과 같으니 확인 바랍니다.

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="./jui-develop/jui-develop/jui.css" />
	<script src="./jui-develop/jui-develop/lib/jquery-1.8.0.min.js"></script>
	<script src="./jui-develop/jui-develop/jui.js"></script>
</head>
<body class="jui">

	<script id="tpl_tooltip" type="text/template">
		<div class="tooltip tooltip-top tooltip-black">
			<div class="anchor"></div>
			<div class="message"><!= obj.dataKey !>: <!= obj.data[obj.dataKey] !></div>
		</div>
	</script>


<script id="script_code">
var chart = jui.include("chart.builder");
var activeIndex = 0,
    data = [
        { quarter : "1Q", samsung : 50, lg : 35, sony: 10 },
        { quarter : "2Q", samsung : 20, lg : 30, sony: 5 },
        { quarter : "3Q", samsung : 20, lg : 5, sony: 10 },
        { quarter : "4Q", samsung : 30, lg : 25, sony: 15 }
    ];

chart("#chart-content", {
    series : {
        samsung : {
            color : 0,
            text : "Samsung"
        },
        lg : {
            color : 1,
            text : "LG"
        },
        sony : {
            color : 2,
            text : "SONY"
        }
    },
    axis : {
        x : {
            type : "range",
            domain : function(data) {
                return data.samsung + data.lg + data.sony;
            },
            line : true,
            orient: "top"
        },
        y : {
            type : "block",
            domain : "quarter",
            line : true
        },
        data : data
    },
    brush : {
        type : "stackbar",
        active : activeIndex,
        activeEvent : "click",
        target : [ "samsung", "lg", "sony" ]
    },
    widget : [{
        type : "title",
        text : "Bar Sample",
        orient : "bottom",
        align : "end"
    }, {
        type : "legend",
        filter : true
    }],
    event : {
        "mousedown" : function(d) {
            activeIndex = d.dataIndex;
        },
        "legend.filter" : function(target) {
            this.updateBrush(0, { active: activeIndex });
        }
    }
});

	})
</script>


</body>
</html>

**Comment by easylogic** [comment]
일단 comment 코드 highlight 기능 써서 살짝 수정했으니 이해바랍니다.

**Comment by easylogic** [comment]
아래 코드 적용해보세요. 

```javascript
var chart = jui.include("chart.builder");
    var activeIndex = 0,
            data = [
                { quarter : "1Q", samsung : 50, lg : 35, sony: 10 },
                { quarter : "2Q", samsung : 20, lg : 30, sony: 5 },
                { quarter : "3Q", samsung : 20, lg : 5, sony: 10 },
                { quarter : "4Q", samsung : 30, lg : 25, sony: 15 }
            ];

    chart("#chart-content", {
        height : 300,
        series : {
            samsung : {
                color : 0,
                text : "Samsung"
            },
            lg : {
                color : 1,
                text : "LG"
            },
            sony : {
                color : 2,
                text : "SONY"
            }
        },
        axis : {
            x : {
                type : "range",
                domain : function(data) {
                    return data.samsung + data.lg + data.sony;
                },
                line : true,
                orient: "top"
            },
            y : {
                type : "block",
                domain : "quarter",
                line : true
            },
            data : data
        },
        brush : {
            type : "stackbar",
            active : true,   // 여기는 참고로 true, false 개념입니다. 나머지는 내부에서 처리합니다. 
            activeEvent : "click",    // click 을 할 때 activeIndex 가 자동으로 옮겨집니다. 
            target : [ "samsung", "lg", "sony" ]
        },
        widget : [{
            type : "title",
            text : "Bar Sample",
            orient : "bottom",
            align : "end"
        }, {
            type : "legend",
            filter : true
        }]
    });
```

**Comment by jinammin** [comment]
해당 코드로 동작 테스트를 해보았으나 마찬가지로 화면에 아무것도 나오지 않습니다. 제 코드를 올릴테니 여기에서 어떤 것이 문제인지 확인해주실 수 있으신가요?

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="./jui-develop/jui-develop/jui.css" />
	<script src="./jui-develop/jui-develop/lib/jquery-1.8.0.min.js"></script>
	<script src="./jui-develop/jui-develop/jui.js"></script>
</head>
<body class="jui">

	<script id="tpl_tooltip" type="text/template">
		<div class="tooltip tooltip-top tooltip-black">
			<div class="anchor"></div>
			<div class="message"><!= obj.dataKey !>: <!= obj.data[obj.dataKey] !></div>
		</div>
	</script>


<script id="script_code">
var chart = jui.include("chart.builder");
    var activeIndex = 0,
            data = [
                { quarter : "1Q", samsung : 50, lg : 35, sony: 10 },
                { quarter : "2Q", samsung : 20, lg : 30, sony: 5 },
                { quarter : "3Q", samsung : 20, lg : 5, sony: 10 },
                { quarter : "4Q", samsung : 30, lg : 25, sony: 15 }
            ];

    chart("#chart-content", {
        height : 300,
        series : {
            samsung : {
                color : 0,
                text : "Samsung"
            },
            lg : {
                color : 1,
                text : "LG"
            },
            sony : {
                color : 2,
                text : "SONY"
            }
        },
        axis : {
            x : {
                type : "range",
                domain : function(data) {
                    return data.samsung + data.lg + data.sony;
                },
                line : true,
                orient: "top"
            },
            y : {
                type : "block",
                domain : "quarter",
                line : true
            },
            data : data
        },
        brush : {
            type : "stackbar",
            active : true,   // 여기는 참고로 true, false 개념입니다. 나머지는 내부에서 처리합니다. 
            activeEvent : "click",    // click 을 할 때 activeIndex 가 자동으로 옮겨집니다. 
            target : [ "samsung", "lg", "sony" ]
        },
        widget : [{
            type : "title",
            text : "Bar Sample",
            orient : "bottom",
            align : "end"
        }, {
            type : "legend",
            filter : true
        }]
    });

	})
</script>


</body>
</html>

**Comment by easylogic** [comment]
```javascript
chart("#chart-content", { 
```

현재 화면에 실체로 차트를 표현할 수 있는 id="chart-content"  영역이 없습니다. 

body 밑에 

```html
<div id="chart-content"></div>
```

하나 추가 해주세요.

**Comment by jinammin** [comment]
말씀해주신 대로 body 밑에 해당 코드를 추가하였습니다. 그런데도 화면에 뜨지 않는데, 대체 무엇이 문제가 되는 걸까요?

<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" href="./jui-develop/jui-develop/jui.css" />
	<script src="./jui-develop/jui-develop/lib/jquery-1.8.0.min.js"></script>
	<script src="./jui-develop/jui-develop/jui.js"></script>
</head>

<body>

<div id="chart-content"></div>

	<script id="tpl_tooltip" type="text/template">
		<div class="tooltip tooltip-top tooltip-black">
			<div class="anchor"></div>
			<div class="message"><!= obj.dataKey !>: <!= obj.data[obj.dataKey] !></div>
		</div>
	</script>

<script id="script_code">
var chart = jui.include("chart.builder");
    var activeIndex = 0,
            data = [
                { quarter : "1Q", samsung : 50, lg : 35, sony: 10 },
                { quarter : "2Q", samsung : 20, lg : 30, sony: 5 },
                { quarter : "3Q", samsung : 20, lg : 5, sony: 10 },
                { quarter : "4Q", samsung : 30, lg : 25, sony: 15 }
            ];

    chart("#chart-content", {
        height : 300,
        series : {
            samsung : {
                color : 0,
                text : "Samsung"
            },
            lg : {
                color : 1,
                text : "LG"
            },
            sony : {
                color : 2,
                text : "SONY"
            }
        },
        axis : {
            x : {
                type : "range",
                domain : function(data) {
                    return data.samsung + data.lg + data.sony;
                },
                line : true,
                orient: "top"
            },
            y : {
                type : "block",
                domain : "quarter",
                line : true
            },
            data : data
        },
        brush : {
            type : "stackbar",
            active : true,   // 여기는 참고로 true, false 개념입니다. 나머지는 내부에서 처리합니다. 
            activeEvent : "click",    // click 을 할 때 activeIndex 가 자동으로 옮겨집니다. 
            target : [ "samsung", "lg", "sony" ]
        },
        widget : [{
            type : "title",
            text : "Bar Sample",
            orient : "bottom",
            align : "end"
        }, {
            type : "legend",
            filter : true
        }]
    });

	})
</script>


</body>
</html>
