### ISSUE TITLE
[JUI] Basic Bar Chart: 두 가지 버그와 한 가지 건의 사항 올립니다.

### ISSUE THREAD

**Issue by jinammin** [juijs/jui#278]
안녕하십니까. 저번에 Basic Bar Chart에 값 표기 옵션(display = all)을 개발해주신 덕분에 유용하게 JUI를 사용하고 있는 유저입니다. 당시 글: https://github.com/seogi1004/jui/issues/253

다름이 아니라 이에 대한 두 가지 버그와 한 가지 건의 사항이 있어서 이렇게 글을 올립니다.

버그 1) 총점이 100일 경우에 "100"이라는 글자가 차트 영역 바깥으로 나감에 따라 화면에 보이지 않는 문제(무조건 우측으로만 나와서 발생하는 것으로 여겨집니다.)

버그 2) domain의 값은 코딩하는 순서에 따라 순차적으로 화면에 출력이 됩니다. 다만, data 값은 코딩하는 순서의 역순으로 화면에 출력이 됩니다. 따라서 domain의 값과 data의 값이 일치하지 않는 문제점이 있습니다.

건의 사항 1) 15개의 domain을 사용하여 그래프를 표기함에 따라 한 차트 내에서 15개의 Bar가 동일한 색상을 가집니다. 따라서 확연한 구분이 힘든 문제가 있습니다. 이에 대해 '각각의 Bar별로 색상을 조정할 수 있는 기능' 혹은 'Bar의 data 수치에 따라 색상을 조정할 수 있는 기능(0~50점은 노란색, 51~100점은 파란색처럼)' 들을 추가해주실 수 있으신지 궁금합니다.

JUI 덕분에 웹 사이트를 개발함에 있어 많은 도움을 받고 있습니다. 그러다보니 JUI에 대해 애정이 생겨 여러가지 건의를 하게 되었습니다. 애정을 가진 사용자로서 앞으로 JUI가 더욱 발전할 모습을 기다리며 항상 응원하겠습니다! JUI 개발진들 화이팅!

**Comment by easylogic** [comment]
JUI 많은 관심 감사드립니다. 

버그 1) 은 샘플 코드를 같이 올려주시면 감사하겠습니다. 

버그 2)  어떤 차트에서 발생하시나요?  fullstackbar 가 순서가 안맞네요. ㅠㅠ 

건의사항 1)   현재는 target 별로 색상을 지정하는 기능 밖에 없습니다.  그려지는 index  또는 다른 값에 따른 색상은 구현 해야할 것 같습니다. 

관련해서 필요한 부분 이슈로 등록하고 처리 되면 말씀드릴게요.

**Comment by jinammin** [comment]
버그 1과 2는 동일한 Basic Bar Chart 상에서 일어나는 문제이기에 두 가지를 확인할 수 있도록 코드 올립니다. 확인하셔서 개선해주시면 감사하겠습니다.

<div id="chart"></div>

<script id="tpl_tooltip" type="text/template">
    <div class="tooltip tooltip-top tooltip-black">
        <div class="anchor"></div>
        <div class="message"><!= obj.dataKey !>: <!= obj.data[obj.dataKey] !></div>
    </div>
</script>


<script id="script_code">
    jui.ready([ "chart.builder" ], function(chart) {

        chart("#chart", {
            icon: {
                path: "../../img/icon-list"
            },
            width: 640,
            height : 400,
            axis : [
                {
                    data : [

						{ A : 10 },
						{ A : 20 },
						{ A : 30 },
						{ A : 40 },
						{ A : 50 },

						{ A : 60 },
						{ A : 70 },
						{ A : 80 },
						{ A : 90 },
						{ A : 100 },
					],
                    y : {
                        orient : 'left',
                        domain : [ 
						"1. ", 
						"2. ", 
						"3. ", 
						"4. ", 
						"5. ", 
						"6. ", 
						"7. ", 
						"8. ", 
						"9. ", 
						"10. "
						],
			line : true,
                        color : "#bbbbbb"
                    },
                    x : {
                        type : 'range',
//			line : true,
			color : "#bbbbbb",
                        domain : [ 0, 100 ],
                        step : 10
                    }
                }
            ],
/*            widget : [
            	{ type : 'title', text: "문제 유형별 본인 점수" },
            	{ type : 'legend' },
                {
                    type : 'tooltip',
                    format : function(k, v) {
                        return this.icon("gear") + " " + v + "점";
                    }
                }

            ],
*/
			padding : {
				left : 270,
				right : 10,
				top : 0
			},
            brush : {
                type : 'bar',
                target : ['A'],
		display : "all",
		colors : [ 4 ]
            },
            style : {
                barBorderWidth : 1,
                barBorderColor : "black",
                barBorderOpacity : 0.3
            }
        });
	})
</script>

**Comment by jinammin** [comment]
빠른 처리에 항상 감사드립니다!

**Comment by easylogic** [comment]
아래 코드 먼저 적용해보세요. 

일단 brush 마다 기본으로 clip 모드가 들어가있어서 그리는 범위를 넘어선 값이 보이지 않을 때가 있습니다. 

이때는 clip : false  옵션을 주시면  그려지는 모든 항목이 다 보입니다. 

다만  padding 에 영향을 받기 때문에  chart.padding 을 잘 조절 하시면 될 것 같아요. 

ps. 데이타가 역순으로 보인다는건 어떤것을 말씀하시는건가요? 

```html

<script id="script_code">
    jui.ready([ "chart.builder" ], function(chart) {

        chart("#chart", {
            icon: {
                path: "../../img/icon-list"
            },
            width: 640,
            height : 400,
            axis : [
                {
                    data : [

                        { A : 10 },
                        { A : 20 },
                        { A : 30 },
                        { A : 40 },
                        { A : 50 },

                        { A : 60 },
                        { A : 70 },
                        { A : 80 },
                        { A : 90 },
                        { A : 100 },
                    ],
                    y : {
                        orient : 'left',
                        domain : [
                            "1. ",
                            "2. ",
                            "3. ",
                            "4. ",
                            "5. ",
                            "6. ",
                            "7. ",
                            "8. ",
                            "9. ",
                            "10. "
                        ],
                        line : true,
                        color : "#bbbbbb"
                    },
                    x : {
                        type : 'range',
//          line : true,
                        color : "#bbbbbb",
                        domain : [ 0, 100 ],
                        step : 10
                    }
                }
            ],
            padding : {
                left : 270,
                right : 50,
                top : 0
            },
            brush : {
                type : 'bar',
                target : ['A'],
                display : "all",
                colors : [ 4 ],
                clip : false
            },
            style : {
                barBorderWidth : 1,
                barBorderColor : "black",
                barBorderOpacity : 0.3
            }
        });
    })
</script>
```

**Comment by jinammin** [comment]
버그 1)의 경우 말씀해주신 것처럼 clip 설정과 right padding 조절을 통해 해결했습니다. 감사합니다.

버그 2의 경우 조금 더 상세하게 설명해드리자면, 코드 상에서 보면 data 값이 A : 10, ~~~ A : 100 처럼 오름차순 정렬된 것을 알 수 있습니다. 그러면 domain 1에는 10이라는 값이 들어갈 것이고, domain 10에는 100이라는 값이 들어갈 것이라 생각하는게 당연하겠죠?
다만, 그래프를 확인해보면 역으로 domain 1에 100이 들어가있고, domain 10에는 10이 들어가있음을 확인할 수 있습니다. 이러한 현상을 데이터가 역순으로 보인다라고 기술한 것입니다.

**Comment by easylogic** [comment]
일단 형식은 말씀하신 형식이 맞습니다. 
제쪽에서 직접 코드를 테스트 해봤을 때는 순서대로 나왔었습니다. 

이건 좀 더 자세히 확인 해봐야겠네요.

**Comment by jinammin** [comment]
네~ 현제 제가 갖고 있는 (나름 최신 버전이라고 생각중인)버전에서는 버그 2의 현상이 뚜렷하게 발생하고 있습니다. 이미지가 업로드되면 보여드리기 편할텐데요. 자세히 확인해보시고 결과 말씀 부탁드립니다. ^^
