### ISSUE TITLE
Components API 페이지 복원 요청

### ISSUE THREAD

**Issue by ninetails9** [juijs/jui#287]
예전에는 http://seogi1004.github.io/jui/ko/index.html 에서 Components 페이지에 각 Component 별로 API 설명 페이지가 존재 했었는데 지금은 Components 예제 페이지(http://seogi1004.github.io/jui/res/uiplay/index.html) 로 모두 링크를 시키셨네요.
물론 API 문서 페이지(http://api.jui.io)가 별도로 존재하지만 예전 API 문서 페이지의 내용을 모두 담고 있지 않는 듯 합니다. 예를 들면 uix.table 예제에는 unchecked 와 checked Method 를 사용하고 있는데 http://api.jui.io 에서는 uxi.table API 문서에서 찾을 수가 없습니다.
예전 Components API 페이지를 볼 수 있는 방법이 없을까요?

**Comment by seogi1004** [comment]
관련 페이지는 존재하므로 아래 링크를 참고하시면 될 것 같습니다.
기존의 API 문서를 노출시키는 방법에 대해서는 고민을 해보겠습니다.

http://seogi1004.github.io/jui/ko/script/table_api.html
