### ISSUE TITLE
line 차트 관련 요청사항 (split line 멀티 라인 지원)

### ISSUE THREAD

**Issue by Kimyoungchan** [juijs/jui#320]
안녕하세요~ 
JUI에서 Leave a comment가 작동되지 않아 여기에 질문드립니다.

현재 JUI차트 잘 사용하고 있는데, 다음 기능이 가능한지 궁금해서 문의드립니다.
제가 하고싶은 작업은 라인차트에서 라인의 색을 x축의 구간별로 다르게 지정하고 싶습니다.
예를 들어 x축에 일별 데이터가 (1일, 2일, ... 8일) 있을때(그래프에 있는 라인은 한개입니다.)
1일부터 3일까지는 빨간색
4일부터 6일까지는 검정색
7일부터 8일까지는 파란색
이런식으로 같은라인의 색을 지정하고 싶은데,
어떠한 방법이 있을지 궁금합니다. 

확인 부탁드리겠습니다..

**Comment by easylogic** [comment]
http://seogi1004.github.io/jui/res/chartplay/index.html#split_line.js 

비슷한 종류로 라인을 두가지 색상으로 쪼개는 차트는 있습니다만 아직  여러개의 구역으로 나누는 라인 차트는 없습니다. 

지금 현재 방식으로 한다면  좀 복잡하지만 구현은 가능합니다. 
비슷하게 흉내를 낼수는 있습니다. 

아래 두개 예제를 참고하세요. 

https://github.com/seogi1004/jui/blob/develop/sample/chart/date_split_multi_line.html
https://github.com/seogi1004/jui/blob/develop/sample/chart/fullblock_split_multi_line.html


구현 방식은 

전체 축(axis) 를 3개로 (또는 색상 분리를 원하는 개수만큼)  만들고 
그에 맞는 데이타를 추가해주고 
브러쉬를 각각 그려줍니다. 

그럼 라인이 구분되어진 것 처럼 보여요.

**Comment by seogi1004** [comment]
splitline 브러쉬가 제공되긴 하지만 색상 표현이 두가지 밖에 안되서 개선을 해야할 것 같네요.

**Comment by Kimyoungchan** [comment]
답변 감사합니다~~
