### ISSUE TITLE
Axis에 데이터가 배열이 아닌 객체일 경우에 대한 처리

### ISSUE THREAD

**Issue by seogi1004** [juijs/jui#341]
브러쉬에 옵션으로 페이스 값을 넣으니 딥클론 하는 문제를 진호형이 발견을 해서;;
폴리곤 값을 아무래도 데이터로 넣는게 좋을 것 같음...

현재 Axis의 데이터 핸들링은 모두 데이터가 배열이다라고 가정하에 구현되어 있음...
관련해서 객체일 경우에 처리하는 코드를 넣어야 겠음...

예를 들면 객체일 경우 render를 안한다는 버그같은 것들...

**Comment by easylogic** [comment]
그러지 말고 

brush 옵션에 omit 이라고 하나 두자. 

```javascript
brush : {
    faces : faces,
    omit :  { 'faces' : true  }  // deepClone 대상에서 제외  
}
```

이러면 거의 고칠게 없음 

_.deepClone(brush, brush.omit);

두번째 매개변수만 추가 하면 끝남

**Comment by seogi1004** [comment]
@easylogic 이것때문에 굳이 저런 옵션을 둘 이유가 없음;;
어차피 그리드 개편하면 많이 바뀌긴해야함...

**Comment by easylogic** [comment]
단순 객체가 아니라 Model 에 대한 개념을 먼저 적립해봅세.. 

data : model 

형태로 가는게 좋을 듯 .

**Comment by easylogic** [comment]
모델 모델 변하지 않는 모델 ~
