### ISSUE TITLE
table expand all 

### ISSUE THREAD

**Issue by yuhwkim** [juijs/jui#350]
테이블에서 하나의 로우만 확장이 되는데. 전체를 모두 확장할 수 있는 방법에는 뭐가 있나요. 

또, 확장된 row 를 hide 시키지 않는 방법은 없나요?

**Comment by ahacross** [comment]
전체 확장하는건 없는거 같아요. 

저도 필요해서 모든 row 확장하는건 만들었는데 그냥 참고만 하세요~ 

this.showExpandAll = function() {
	for(var i=0, n=this.count(); i<n; i++){
		var expandSel = "#EXPAND_" + this.timestamp+"_"+i,
			obj = undefined,
			row = this.get(i),
			obj = (typeof(obj) != "object") ? $.extend({ row: row }, row.data) : obj;
        
		$(row.element).after('<tr class="expand"><td id="'+expandSel.substring(1)+'"></td></tr>');
        
        $(expandSel)
        	.attr("colspan", $obj.thead.find("tr:last > th:visible").size())
        	.html(this.tpl["expand"](obj));     
	}

    // 스크롤 및 VO 적용
    this.scroll();
    this.setVo();
}
