### ISSUE TITLE
scatterpath 이용시

### ISSUE THREAD

**Issue by javapark** [juijs/jui#356]
데이터의 형태가 다음과 같습니다.
[{'time':'2015-09-15 14:26', 'a':50}, {'time':'2015-09-15 14:28', 'b':40}, {'time':'2015-09-15 14:36', 'c':30}]

이때 scatterpath 로 a, b, c 를 각각 타겟으로 지정하여 출력시 9개의 데이터가 출력되고 데이터가 없는 것은 최상단에 위치하는 것을 확인하였습니다. 
이와 관련하여 데이터 출력시 a, b, c에 대한 즉, 값이 있는 필드에 대해서만 출력할 수 있는 방법이 있을까요?
방법을 좀 알고 싶습니다.

**Comment by easylogic** [comment]
a, b, c 로 나눠서 하시는 이유가 있으신가요? 

현재로서는 target 을 지정하게 되면 값이 없더라도 하나의 값으로 처리하게 됩니다. 

만약에  a,b,c 를 다르게 하고 싶어서 쓰시는 것이면 

데이타 구조를 아래와 같이 나눠서 쓸 수 있습니다.  

a = []  // a 데이타만 있는 obj 
b = [] 
c = [] 

```javascript
{
    axis : [
       { x , y , data : a },
       { x , y , data : b },
       { x , y , data : c }  
    ],

    brush : [
        { type : 'scatterpath', axis : 0, target : 'a' },
        { type : 'scatterpath', axis : 1, target : 'b' },
        { type : 'scatterpath', axis : 2, target : 'c' },
    ]
}
```

참고로 axis 도 여러개, brush 도 여러개 지정가능 하기 때문에 
각각에 맞게 구성할 수가 있습니다. 

있는 필드에 대해서만 값을 표시 하는 부분은 고민을 좀 해보겠습니다. 
jui 전체 공통된 부분이라  필요할 수도 있을 것 같아요.

**Comment by javapark** [comment]
네. 감사합니다. ^^

추가로 scatterpath 클릭이벤트 적용은 못하는 것인가요?
도저히 찾아봐도 scatterpath 만 이벤트를 적용할 수 없어보입니다. 

도움 부탁드리겠습니다.
