### ISSUE TITLE
차트 파이어폭스 버그

### ISSUE THREAD

**Issue by yuhwkim** [juijs/jui#357]
1.4.1 버전 샘플 모두 테스트 해보지는 않았지만, 

일단 토폴로지 샘플의 경우 

파이어폭스 : 드래그 안됨 / 선택 시 좌상단으로 초기화 되는 듯한 버그 / 줌 안됨 
익스 11 : 줌 시 컨테이너 밖으로 벗어나서 확대됨. 
크롬 : 잘됨. 

예전부터 파이어폭스에서는 차트 오류가 여러가지 발생하는 데, 확인 좀 부탁드립니다. 
토폴로지 말고도, svg에 필요한 데이터에서 오류가 좀 있는 거 같아요. 

--------------------------------------------------
그리고 여기는 거의 두분이서 이슈를 올리고 계신데 
메인 개발자 분들이신가요? 

혹시 다른 커뮤니티나 포럼은 없습니까? 
블로그에 있는 글들은 설명이 너무 짧은 것 같습니다. 

play 부분도 좋지만, 튜토리얼을 따로 두시면 더 좋겠네요. 
그리고, API 부분 설명도 조금 보충되었으면 좋겠습니다. 

회사에서 프로젝트 샘플 만드는데 jui 를 사용하고 있는데, 
개발자분들 열정도 느껴지고, jui 스토어도 만들어지는 거 보니까
jui 한 번 제대로 파보고 싶네요. 
아무튼, 
상당히 잘 만든 라이브러리 같습니다. 수고하셨고, 앞으로도 힘내 주십시오.

**Comment by easylogic** [comment]
파폭 , ie 관련 이벤트는 다시 점검해보겠습니다. 

-------------------------

현재는 개발자가 두 명입니다. 

아직까지는 외부에서 참여(Pull Request)하는 적이 없어서 사실상 두명이 하신다고 보시면 됩니다. 

업무와 같이 하다 보니  사실 여유가 만이 없는 상태입니다. 

그래서 아직까지는 많이 부족한 부분이 있습니다. 

그러한 부분을 해결해보고자. chartplay, uiplay,  store 등등을 기획하게 되었고 좀 더 다듬어갈 생각입니다.

따로 포럼을 열어둔 곳은 없고  페이스북에 그룹(https://www.facebook.com/groups/juijs/)이 하나 있습니다. 

그쪽으로 간단한 질문이나 이슈를 남겨주셔도 됩니다. 

버그들은 최대한 처리할 수 있는 방향으로 생각하고 있습니다. (일정을 다 예상을 하지는 못하지만)

앞으로 좀더 튜토리얼 성격의 문서가 계속 만들어질 계획에 있습니다. 

저희가 생각해도 문서가너무 없다 보니 사용하시는데 불편한 점이 많을 것 같아요. 

앞으로도 노력 많이 하겠습니다. 

잘 지켜봐주세요 ~
