### ISSUE TITLE
안녕하세요 사용중에 table, window등을 생성 후에 초기화(삭제)는 어떻게 하나요?

### ISSUE THREAD

**Issue by ahacross** [juijs/jui#363]
질문을 좀더 풀어 써 보자면.

생성
table1 = jui.uix.table("#table1", { 
window1 = jui.uix.window("#window1", { 

이렇게 생성하여 사용합니다. 

사이트 구조가 ajax로 load로 붙여서 다른 페이지를 호출하는 구조인데요.
같은 페이지로 다시 들어오면 table이 표시가 되지 않는 현상이 있습니다. 

새로고침을 하면 잘 되는 것을 보아서는 
기존에 생성된 정보가 있어서 문제인거 같은데요. 

저렇게 생성된 table1 을 어떻게 없애야 할까요?

단순히 delete table1 은 계속 동일하게 표시가 안됩니다.
어떻게 초기화(삭제)를 해줘야 할까요?

**Comment by easylogic** [comment]
@ahacross 안녕하세요. 

jui 에서 생성된 객체를 삭제할때는 

```javascript
table1.destroy()
```

를 실행해주시면 됩니다. 

delete table1 의 경우는  delete 가 객체 자체를 지우지 못하기 때문에 아무 동작을 안합니다. 

참고하세요 ~

**Comment by ahacross** [comment]
table1.destroy() 로 삭제를 하고 난 후에도 console 에서 table1을 쳐보면 그대로 살아있습니다.

어떻게 해야 깨끗하게 지울 수 있을까요?

**Comment by easylogic** [comment]
그러고 보니 destroy 는 내부 자원을 없애는거네요. 

```javascript
table1.destroy();
table1 =  null; 
```

형태로 직접 값을 셋팅 해주시면 될 것 같습니다.

**Comment by ahacross** [comment]
우선 메뉴를 누르면 모든 window~ 와 table~들을 destroy() 하고 null 이 되게끔 처리했습니다. 
그럼에도 불구하고 window 안에 있는 table에 데이터가 표시되지 않았습니다. 

이런 테스트를 해 보았습니다.

윈도우를 닫지 않은 채 같은 페이지로 다시 들어와서 윈도우를 새로 띄웠더니 
나중에 띄운 윈도우의 table은 데이터가 표시되지 않았고 
처음에 띄운 윈도우의 table에 데이터가 표시 되었습니다. 

이걸 어떻게 해야 나중에 띄운 윈도우의 table에 데이터를 표시할 수 있을까요?
(처음에 띄운 window와 table은 이미 destroy와 null을 적용한 상태입니다.)

**Comment by easylogic** [comment]
실제 사용하신 코드를 보여주실 수 있으신가요? 

윈도우 안에서 table 객체가 생성 될 때 혹시 id 나 같은 클래스로 정의되면 한번에 다 같이 객체를 생성하기 때문에 

이전 객체가 계속 살아있을 수 있어요. 

실제 코드를 봐야 이해할 수 있을 듯 합니다.

**Comment by ahacross** [comment]
table html 입니다.
<table id="window1Tab2Table1" class="table simple hover stripeless">
		<thead>
			<tr>
				<th width="10%">어플리케이션</th>
				<th width="10%">로그 ID</th>
				<th width="*">로그 라인</th>
				<th width="60px">선택</th>										
			</tr>				
		</thead>
  			<tbody></tbody>
	</table>

<script data-jui="#window1Tab2Table1" data-tpl="row" type="text/template">
    <tr>
		<td class="center"><!= appName !></td>		
		<td class="center"><!= logFormatId !></td>		
		<td class="center"><!= convertAngleBracket(addLogLine) !></td>
		<td class="center"><a class="btn">선택</a></td>
    </tr>
</script>
<script data-jui="#window1Tab2Table1" data-tpl="none" type="text/template">
    <tr>
        <td colspan="4" class="none" align="center">데이터가 없습니다.</td>
    </tr>
</script>

테이블 생성하는 부분이고요. 
window1Tab2Table1 = jui.uix.table("#window1Tab2Table1", {}); 

생성한 테이블은 아래와 같은 refresh_window1Tab2Table1 을 실행해서 update해 줍니다.
after.body.rowData란 곳에 데이터가 객체로 들어가 있고요.

var refresh_window1Tab2Table1 = function(){
		ajax.run(function(after, before){
			window1Tab2Table1.update(after.body.rowData);
		}); 
	}

juiInit.all()이란걸 메뉴가 이동할 때(다른 페이지를 load하기 전)마다 실행합니다.
이걸로 window 객체에 있는 window와 table들을 destroy, null 합니다.

var juiInit = (function(){
	var destroy = function(name, target){
		var type = target && target.type;
		
	/*	if(type && type === "show"){
			target.hide();
		}*/
		target && target.destroy(); 
		window[name] = null;   
	}
	
	var all = function(){
		var windowKeys = Object.keys(window),
			windowKey;
		
		for(var i=0, n=windowKeys.length; i<n; i++){
			windowKey = windowKeys[i];
			if(windowKey !== "window" && windowKey !== "table" && (windowKey.indexOf("window") > -1 || windowKey.indexOf("table") > -1)){
				destroy(windowKey, window[windowKey]);
			}
		}
	}
	return {
		all		: all
	}
}());

소스 부분인데 전체소스가 필요하시면 메일을 알려주시면 보내드리겠습니다.

**Comment by easylogic** [comment]
테이블 생성하실 때 옵션은 따로 안 주시나요?

**Comment by ahacross** [comment]
event 옵션만 줍니다. 

event : {
	select : function(row, e){
              
         }
} 

이정도만 주고 사용합니다.
