### ISSUE TITLE
scatterpath 는 event 적용이 불가한가요?

### ISSUE THREAD

**Issue by javapark** [juijs/jui#364]
scatterpath 를 이용하려고 하는데 클릭이벤트를 적용할 수 없어 보이는데  혹시 방법이 있을까요? 
다량의 데이터를 표시하는데 scatterpath 가 좋은데.. 조금의 제약이 있어 보입니다.
답변기다리겠습니다. 

감사합니다.

**Comment by easylogic** [comment]
사실 표시 용도로 만든거라서  구조상 클릭이벤트로 실제 점을 가지고 오는게 많이 어렵습니다. 
svg  의 path 만을 이용해서 그리는거라 

path 클릭하는 거에 따라 실제 값을 가지고 와야 하는데 그건 좀 힘들구여. 

대신에  scatter 차트와 같이 drag widget 을 사용할 수는 있습니다. 

실제 점 객체가 클릭이 되어야 하나요?

**Comment by javapark** [comment]
네.. 점 객체에 대한 클릭이 필요합니다. 
그리고 혹시 drag 이벤트를 이용하여 영역내의 점의 갯수를 알 수 있을까요?
