### ISSUE TITLE
오거나이저로 이동.

### ISSUE THREAD

**Issue by dalinaum** [juijs/jui#366]
회사나 단체의 오거나이저나 JENNIFER UI를 위한 오거나이저를 만들어서 이전을 추진하면 어떨까요?

오거나이저로 이동하는 것이 유지 보수나 브랜딩을 위해 더 유리할 것으로 생각됩니다.

**Comment by seogi1004** [comment]
juijs로 이전할 예정이긴 합니다만...
그 전에 프로젝트를 차트와 컴포넌트로 분리하는 작업이 필요해서 미루고 있었습니다.

https://github.com/juijs

**Comment by easylogic** [comment]
좋은 말씀 감사합니다.

**Comment by dalinaum** [comment]
@seogi1004 @easylogic :+1:

**Comment by seogi1004** [comment]
프로젝트 분리 전에 오거나이저로 변경했습니다!
