### ISSUE TITLE
도넛차트 연결선(이름 : 값) 중첩 현상 해결법 문의드립니다.

### ISSUE THREAD

**Issue by capscharisma** [juijs/jui#368]
안녕하세요 이슈사항을 항상 신경 써주셔서 감사합니다. JUI를 잘 사용하고 있습니다.
한개 여쭤볼게 있는데요~~아래 도넛차트를 사용하다가 한값이 일방적으로 크고 나머지 여러개가
매우 작을 때 연결선에 보이는 참조(이름 : 값) 이 중첩되서 보이는 현상이 있는데 
연결선의 길이와 각도를 제가 조절하면 어느정도 방지가 가능할 것 같아서 문의드립니다.
api를 뒤져봐도 연결선의 각도와 선 길이, 색상등을 컨트롤하는 부분을 못찻아서 
문의드립니다. 

항상 고맙습니다~감기 조심하세요

![default](https://cloud.githubusercontent.com/assets/13570118/10604935/d29c5ad4-7762-11e5-9ff5-f300e34965ae.jpg)

**Comment by easylogic** [comment]
현재 저 부분 관련해서 속성으로 따로 나와있는 것은 없습니다. 
내부적으로 좌표를 수정해야할 것 같습니다. 
다른 차트들을 참조를 좀 해봐야겠네요.
