### ISSUE TITLE
dragselect 이벤트 문의

### ISSUE THREAD

**Issue by javapark** [juijs/jui#371]
dragselect 이벤트를 사용하면서 문의사항이 있어서 글을 올립니다.

1. 차트 내부에서 마우스로 드래그를 시작하여 마우스가 차트 밖으로 이동시 
  -  dragselect.end 이벤트 호출이 안되는 현상
  - 강제적으로 현재 영역을 가져올 수 있는 메소드가 있는지?

2. 차트 외부에서 드래그를 시작해서 차트 내부로 이동시 
  - axis 가 시작되는 시점이나 차트외부, 차트내부 연결지점에서 dragselect.start 를 할 수 있는 방법이 있는지?

바쁘시겠지만 답변 부탁드리겠습니다.

참고로 scatterpath에 적용해서 영역 정보를 가져오는데 위의 현상으로 2% 부족한 느낌이드네요~
98%는 만족하며 잘 사용하고 있습니다. ^^

**Comment by easylogic** [comment]
1. 차트 밖으로 이동하면 axis 의 영역 밖이기 때문에 이벤트가 발생안할 가능성이 있습니다. 이 부분은 구조를 다시 봐야할 것 같아요. 

2. 강제적으로 현재 영역을 가지고 올 수 있는 메소드는 현재 없습니다. 
drag select 의 기능 자체가 정해진 영역으로 x축, y축 비교해서 해당 데이타를 모두 검색하는 방식입니다. 
즉 특정 영역을 알고 계시다면 data 를 실제로 검색하시는게 더 빠를 수 있습니다.

3. 현재는 저희가 멀티 axis 를 구현 할 수 있는 구조라  하나의 차트에 여러개의 영역으로 그릴 수 있습니다. 
    그래서 위젯도  어느정도 axis 에 종속성을 가지고 있어요. 이벤트 구조가 axis 랑 맞물려 있어서  다시 고민을 좀 해봐야겠네요. 

도움 되는 답변이 없네요. ㅠㅠ

**Comment by easylogic** [comment]
axis  가 하나 일때는 전체로 보고 드래그 하는것도 괜찮겠네요.
