### ISSUE TITLE
Chart의 legend filter를 사용했을 때 몇개가 on 시킬 수 있나요?

### ISSUE THREAD

**Issue by metocherry** [juijs/jui#380]
# Chart Legend 속성 관련 문의

chart의 legend filter 속성을true 사용시 default 몇개만 on 시키고 나머지는 off 시키고 싶은데 방법이 있는지 궁급합니다.

현재 제가 적용하고 싶은 것은 

    brush: [
        { 
            type: "column", 
            target: ["FUNNEL", "FORECAST", "COMMIT", "COST", "MARGIN"], 
            colors: [0, 1, 2, 3, 4], 
            animate: true
    ]

인데 처음 ["FORECAST, "COMMIT", "MARGIN"] 가 rendering 되고, ["FUNNEL", "COST"]는 rendering 되지 않고, legend filter에서 off되어 있는 상태로 표시하고 싶습니다.

구현이 가능한지 궁금하고, 가능하다면 어떻게 구현이 가능한지 궁금합니다.

**Comment by seogi1004** [comment]
filter 옵션을 배열 형태로 target을 넣으면, 초기 필터링 세팅되게 추가 개발을 해야겠네요. ㅠㅠ
