### ISSUE TITLE
Chart legend filter 오류

### ISSUE THREAD

**Issue by metocherry** [juijs/jui#382]
chart legend filter와 tooltip을 사용했습니다. filter를 toggle 했을 시 차트 가운데를 중심으로 왼쪽 부분은 마우스 오버시 툴팁이 잘 나오나 오른쪽 부분은 나오지  않고, 마우서 커서가 포인트 모양으로 변합니다. 클릭시 동작했던 필터가 toggle 됩니다.

이와 같은 현상은 크롬에서는 문제가 없이 잘 동작했고, IE 엣지에서 오류가 발생하였습니다.

ps. chart play에서 동일한 현상이 발생합니다.

**Comment by easylogic** [comment]
이슈 감사합니다.  확인 해볼게요.
