### ISSUE TITLE
Layout 클래스 개선 

### ISSUE THREAD

**Issue by easylogic** [juijs/jui#395]
<img width="1020" alt="2015-11-28 8 28 21" src="https://cloud.githubusercontent.com/assets/591983/11451589/a1012d68-960e-11e5-8580-b46b8857d076.png">

이정도는 아주 쉽게 구성할 수 있어야한다.

**Comment by easylogic** [comment]
draggable 객체가 필요할 듯

**Comment by seogi1004** [comment]
올!
