### ISSUE TITLE
webpack과 browserify를 사용할 때 문제가 발생합니다.

### ISSUE THREAD

**Issue by metocherry** [juijs/jui#400]
1. webpack
    - jui.define 을 찾을 수 없다는 오류가 발생합니다.
    - window.jui.define을 써서 오류를 해결하면 webpack 내부 오류라고 하긴 하는데 amd의 'define cannot be used indirect.' 라는 오류가 발생합니다.

2. browserify
    - jQuery를 찾을 수 없다고 나옵니다.

webpack과 brwoserify를 사용하는 경우 이 오류를 해결하는 방법이 있나요?

**Comment by easylogic** [comment]
이슈 감사합니다. 

아직 webpack 이랑 browserify 쪽으로는 테스트를 하지 못하였습니다. 

npm, bower, jamjs 형태로만 지원을 합니다. 

따로 테스트 해서 알려드릴게요. ~

**Comment by easylogic** [comment]
webpack 쪽을 살펴 봤는데요.  

흠 내부적으로 jui 가 jquery 디펜던시를 가지고 있어서 

global.jQuery  형태로  global 에 jquery 가 들어가있어야하네요. 

```javascript
global.jQuery = require('jquery');
require('jui');

```

webpack 의 경우 저런 형식으로 구성이 되어야 할 것 같습니다. 

관련해서 자연스럽게 되도록 구조를 좀 다듬어볼게요.

**Comment by metocherry** [comment]
현재 저는 webpack.ProvidePlugin을 사용하여 자주 사용하는 라이브러리는 require없이 사용하고 있습니다. 우선 알려주신 방법으로 사용해보겠습니다.

답변 감사합니다.
