### ISSUE TITLE
엑셀에서 제작한 이 그래프들을 JUI로 구현할 수 있을까요?

### ISSUE THREAD

**Issue by jinammin** [juijs/jui#406]
안녕하세요. JUI를 애용하고 있는 개발자입니다.
이번에 엑셀로 만든 아래의 보고서(텍스트+그래프)를 웹 상에서 구현하려고 하는데
1) 해당 그래프들이 JUI 상에서 구현이 가능한지, 2) 가능하다면 어느선까지 가능한지, 3) JUI 상에서의 해당 차트 이름은 무엇으로 되어있는지, 4) 차트와 차트 사이에 텍스트로 구분을 할 수 있는지가 궁금합니다.

http://inselllab.com/template/PLUGIN_service/resource/1.png
http://inselllab.com/template/PLUGIN_service/resource/2.png
http://inselllab.com/template/PLUGIN_service/resource/3.png

올려둔 URL에는 총 4가지의 그래프 유형이 나오는데, 이것들이 JUI로 개발이 된다면 모든걸 웹상에서 자동화하여 사용하고자 합니다.
검토해보신 후에 질문에 대한 답변 부탁드리겠습니다 ^^

**Comment by easylogic** [comment]
1번은 새로 구현 해야하구여 

2번은 아래 예제를 보시면 됩니다. 
http://juijs.github.io/jui/res/chartplay/#radar.js

**Comment by easylogic** [comment]
3번은 라인 차트를 사용하면 되는데요. 특정 지역의 높이를 선으로 그어주는건 없습니다. 

따로 구현해야할 듯 해요 ~

**Comment by jinammin** [comment]
빠른 답변감사합니다.
2번 이미지의 방사형 그래프는 말씀해주신 예제를 통해서 개발이 가능하겠네요. ^^

몇 가지 질문이 더 있는데요.
A) 1번은 지난 번에 스캐터 차트를 가로로 회전해서 모양이 비슷하게 나오는 것까진 보여주셨는데, 거기에 최소-평균-최대 값을 잇는 선까지 그어주는게 가능할지요?
B) 2번의 방사형 그래프 하단에 있는 점 분포도에 대해서는 어떤 그래프가 사용 가능하려나요?
C) 3번의 경우에 보여주신 라인 차트에 세로형 Bar Chart를 동시에 쓸 수 있는 방법은 없을까요?(엑셀에서도 두개의 그래프로 표현했습니다)
D) 한 페이지 내에 "그래프 1에 대한 별도의 설명문(HTML 이용)", "그래프 1", "그래프 2에 대한 별도의 설명문(HTML 이용)", "그래프 2" 순으로 표현하려면 어떻게 해야하나요? JUI 차트 코드를 연달아 쓰면 차트가 위로 몰리는 현상이 있어서 질문 남깁니다.

답변 부탁드리겠습니다. 감사합니다.

**Comment by easylogic** [comment]
관심 가져주셔서 감사합니다.  ^^ 

A) 의 경우  처럼 할려면  scatter 차트에  라인 차트를 합쳐야 하는데요.  현재는 라인차트 기능중에 중간 영역만 그리는 부분이 없습니다. 부분은 따로 만들던가 해야할 것 같아요. 

B) 점의 분포도는 알고 계신 scatter 차트로 가능하십니다.  어떤 데이타인지 알려주시면 가이드가 가능할 것 같아요. 

C) bar 차트를 특정 영역으로 그리는건 현재는 없습니다. 다만 focus 위젯이 있는데요.  특정 영역으로 주황색 영역을 그려줍니다. 차트랑은 상관 없이 그 위에 보이는 형태라서 말씀 하신거랑은 조금 다를 수 있겠네요.  focus 위젯은 따로 사용법을 올릴게요. 

D) 작성하신 sample 을 보여주실 수 있나요?  jui 차트는 svg 영역을 그대로 이용하는 것이기 때문에. 

svg 가 정확한 넓이와 높이를 가져야합니다.  만약 100% 로 그리고 싶으시면  차트가 그려질 영역 위쪽에 height 가 지정이 되어 있어야해요. 그래야 정확한 높이로 그릴 수 있습니다. 

샘플 알려주시면 이것도 가이드 드릴게요 ~

**Comment by seogi1004** [comment]
1번의 경우 데이터가 어떻게 되어있는지 JSON 형태로 댓글을 달아주시면 구현하는데 도움이 될 것 같습니다.

**Comment by jinammin** [comment]
링크 1번 그래프의 데이터는 아래처럼 구성되어 있어요 ^^ (JSON 형태가 이걸 의미하는게 맞는지 모르겠네요)
domain 값: '영역 1', '영역 2', '영역 3'
data 값: { min: 29, avg: 49, max: 83 }, { min: 33, avg: 41, max: 70 }, { min: 10, avg: 50, max: 90 }

**Comment by jinammin** [comment]
http://inselllab.com/template/PLUGIN_service/resource/2.png
위의 링크에서 가장 마지막에 있는 분포 그래프에 사용한 데이터는 다음 형식처럼 되어있어요~
엑셀로 만들었던 그래프인지라, 테이블 형태로 말씀드릴게요!

| 총점 | 편차 |
| 60.3 | 55  |
|  53   | 50  |
|  41   | 70  |

**Comment by jinammin** [comment]
D) 에 대해서는 현재 만들어둔 Sample이 없어서 기존에 올려두었던 사진으로 설명드릴까하는데요.
http://inselllab.com/template/PLUGIN_service/resource/3.png
해당 링크에 나온 그래프들을 HTML로 간단히 표시해보자면

<h3>SCS에 대한 표준편차 통계 자료</h3>
<br/>
// JUI 그래프 관련 태그 1개(Width: 1000px, Height: 200px로 가정)
<br/>
<h3>세일즈 파이프라인 단계에 대한 표준편차 통계 자료</h3>
<br/>
// JUI 그래프 관련 태그 1개(Width: 200px, Height: 200px로 가정)
// JUI 그래프 관련 태그 2개(Width: 200px, Height: 200px로 가정)
// JUI 그래프 관련 태그 3개(Width: 200px, Height: 200px로 가정)
// JUI 그래프 관련 태그 4개(Width: 200px, Height: 200px로 가정)
// JUI 그래프 관련 태그 5개(Width: 200px, Height: 200px로 가정)
<br/>

링크에 있는 차트들을 페이지 레이아웃 그대로 JUI를 이용해서 만들고 싶은데요.
지난 번에 해보니 위와 같은 방식의 코드로는 원하는 결과물을 얻을 수가 없어서 문의드렸던 거에요~
굳이 표준편차 차트가 아니라 Bar Chart, Scatter Chart 등 어떤 차트를 이용하더라도, A4로 인쇄했을 때 다수의 차트를 그림처럼 담고 싶습니다. 어떤 방법을 통해서 이게 가능할까요?

**Comment by seogi1004** [comment]
@jinammin JUI 차트에서 기본적으로 제공하는 스카터 차트는 X와 Y축을 RANGE로 같이 쓸 수가 없습니다. 같이 쓰려면 브러쉬를 별도로 구현해야하는데요. 제가 아래 링크와 같이 만들어봤습니다.

http://store.jui.io/view.php?id=5674d4fe94976c22078b4567
