### ISSUE TITLE
table에서 remove할 때 "none"부분이 이상해집니다.

### ISSUE THREAD

**Issue by domdomnmadam** [juijs/jui#407]
안녕하세요. 이런 ui component를 오픈해주셔서 무척 감사하고 있습니다. 
개발시 좀더 편하게 개발 할 수 있는 포지션이 있어 아주 편합니다. 

![image](https://cloud.githubusercontent.com/assets/16335535/11868311/280b13c4-a4fa-11e5-9c05-f1840a512deb.png)

일단! 좀 문제가 있어 문의를 드립니다. 

insert, append 시 배열 데이터는 넣을 수 없더군요.

row 형태만 가능한 것 같습니다. 예제는 배열로 되도록 되어 있던데 말이죠...

뭐 어쟀든 listData() 함수를 이용해서 여기에 배열 push를 이용하여 데이터를 넣고 update하는 걸로 해결은 했습니다. 

헌데 row 삭제시 
remove(table.index)를 이요하여 삭제하면 첨부한 파일 처럼 none tpl이 줄어 듭니다. 처음 로딩 때는 잘 나오는데 말이죠.. 

해결점은 없을까요??

**Comment by seogi1004** [comment]
일단 아래 코드를 보세요. 

<script data-jui="#xtable_1" data-tpl="none" type="text/template">
    <tr>
        <td colspan="3" class="none" align="center">Data does not exist.</td>
    </tr>
</script>

기본적으로 jui 테이블 스타일에 none이라는 클래스가 있습니다.
그리고 실제 컬럼 수에 맞게 rowspan을 설정해줘야 합니다.

아래는 해당 코드가 적용된 샘플입니다.
http://jui.io/res/uiplay/index.php#xtable_1
