### ISSUE TITLE
Line Chart에서 라인(값) 클릭시 X축값 가지고 오는 방법 있나요?

### ISSUE THREAD

**Issue by lover74n** [juijs/jui#410]
우선 무료로 양질의 컨텐츠를 제공함에 있어 감사드립니다

궁금한점이 있어 문의드립니다
차트 클릭 이벤트로
event : {
  click : function(obj, e){
       obj.dataIndex; // Index
       obj.data[obj.dataKey] ; //Y축값
  }
}
Y축실제값은 저렇게 받아오니깐 되던데
X축값도 클릭시 얻어와야하는데 어떻게 받아오나요?

**Comment by seogi1004** [comment]
dataIndex가 x축 값이라고 보시면 됩니다!
x축 타입이 블럭이면 아래와 같이 사용할 수 있습니다.

```
var data = [
    { quarter : "1Q", sales : 50, profit : 35 },
    { quarter : "2Q", sales : -20, profit : -30 },
    { quarter : "3Q", sales : 10, profit : -5 },
    { quarter : "4Q", sales : 30, profit : 25 }
];

var xValue = data[obj.dataIndex].quarter;
alert(xValue);
```

**Comment by seogi1004** [comment]
그리고 프로젝트가 변경되었으니 앞으로 차트 관련 이슈는 아래 링크에 올려주세요!
https://github.com/juijs/jui-chart/issues

**Comment by lover74n** [comment]
아~~ 감사합니다. 네 앞으로는 확인잘하고 올리겠습니다 감사합니다
