### ISSUE TITLE
UI Table에서 테이블 타이틀 고정하는 방법 있을까요?

### ISSUE THREAD

**Issue by lover74n** [juijs/jui#412]
무료 배포 감사드립니다.

ui에 테이블을 구현해보면 테이블 헤더(th)부분을 고정하고 싶은데
 <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Location</th>
    </tr>
제니퍼UI에 스크롤 기능을쓰면 고정이 됩니다.
다만 google에서는 스크롤이 생기는데 IE11에서는 생기지 않더라구요..
이런 경우 IE에서 테이블헤더를 고정할 수 있는 방법이 있을까요?

**Comment by seogi1004** [comment]
IE11에서는 스크롤을 쓸 경우, 컬럼 헤더가 고정되지 않는다는 말씀이시죠?

**Comment by lover74n** [comment]
IE11에서는 제니퍼 UI Table에 스크롤 자체가 생성되지 않더라구요..
(
jui.ready([uix.table], function(table){
  table_1 = table("#table_1", {
     data:gridData;
     scroll:true     <-- IE11에서 저 속성이 안되는거 같더라구요..
     ....
   }
});
 (같은소스로 크롬에서는 스크롤바 생성잘됩니다)
그래서 테이블에 따로 스크롤바를 생성해서 썼거든요( style="overflow-y:auto") 
저렇게 따로 생성을해서 쓰면 헤더부분이 고정이 안되서 좀 불편하더라구요..

그래서 문의 드려봅니다

**Comment by seogi1004** [comment]
scrollHeight 옵션을 줘보세요!!!

**Comment by lover74n** [comment]
scrollHeight 속성을 줬는데도 스크롤바가 생성이 되지 않네요
(크롬에서는 잘 나오거든요)
jui.ready([ "uix.table" ], function(table) { <-- 저는 uix.table로 생성했는데
                                        예제에보니 grid.table로 되어 있더라구요. 변경해보니 
                                        grid.table is not loaded 오류 뜨는데 jui.min.js 파일이 
                                        최신파일이 아니라서 그런가요? 인터넷이 안되는 환경이라
                                        파일 다운받아서 쓰고 있거든요..
    table_4 = table("#table_4", {
        scroll: true,
        scrollHeight: 150,
        tpl: {
            row: $("#tpl_row").html()
        }
    });

**Comment by seogi1004** [comment]
1 버전대는 uix.table로 모듈명을 입력하시고, 2 버전대는 grid.table로 하셔야 합니다.
이번에 프로젝트가 분리되었어요!

**Comment by lover74n** [comment]
아.. 그렇군요 넵 감사합니다!!!
