### ISSUE TITLE
paging 질문

### ISSUE THREAD

**Issue by ParkMinKyu** [juijs/jui#413]
xtable이랑 연동된 샘플처럼 xtable과 페이징을 구현 했는데
페이지 이동중 서버에서 신규데이터가 추가되거나 삭제되어
페이지 총count가 변동이 있을경우 reload(table.count)를 호출합니다.

이때마다 페이지 번호가 1페이지로 자동으로 이동되는데
보고있는 페이지 번호는 유지하고 reload() 시키는 방법이 없을까요?

**Comment by seogi1004** [comment]
reload 메소드 호출 후에 page 메소드를 호출해주시면 됩니다.
```
paging_2_xtable.update(result);
        paging_2_xtable.resize();
        paging_2.reload(paging_2_xtable.count());
      paging_2.page(2);
```

**Comment by ParkMinKyu** [comment]
제가 구현을 잘못한건지 해서 다시 질문 드립니다.
샘플은 최초 테이블 로딩시에 디비에서 모든 데이터를 가져온상태로 페이징을 구현했는데
이부분을 페이지 선택 할 때마다 서버에서 데이터를 가져오고 페이징부분을 다시 계산하고 하고 싶은데요

이부분을 
page를 선택 -> page()이벤트에서 서버에서 해당 페이지 데이터 & 총 게시물수를 가져옴 ->
page를 reload(총게시물수)

이런식으로 하게되면 reload() 되면서 1페이지가 자동 호출되서 무한루프 돌듯이 

```javascript
for(true){
reload(총게시물수) ;
 page(1);
}
```
이런식으로 무한 호출이 되어서요.
구현을 잘못한건지 다른방법이 있는지 알고싶습니다.

**Comment by seogi1004** [comment]
당연히 for(true)면 무한루프에 빠지구요.
전체 소스코드를 보여주시면 가이드해드리겠습니다!

**Comment by ParkMinKyu** [comment]
넵 설명을 잘못해서 죄송합니다. 무한루프 돌렸다는건 아니였구요 
아래처럼 작성해놨습니다. ^^;
페이지 이벤트 안에서 ajax로 가져온 totalCnt를 reload하면 무한루프 빠진것처럼 
계속 페이지 호출이 이루어져서 해결방법을 알고 싶습니다.

```javascript
jui.ready([ "uix.xtable","ui.paging" ], function(xtable, paging) {
/**
테이블 설정
*/
    table_1 = xtable("#table_1", {fields: [ "id", "title", "regtime", "writer" ],
        resize: false,
        sort: true,
        sortLoading: true,
        buffer: "s-page",
        bufferCount: 16,
        scrollHeight : 450,
        event: {
            sortend: function(data, e) {
                paging_2.first();
            }
        },
        tpl: {
            row: $("#tpl_row").html()
        }
     });
/**
페이징 설정
*/
    
    paging_1 = paging("#paging_1", {
        pageCount: 16,
        screenCount : 7,
        event: {
            page: function(pNo) {
/**
페이징 이벤트 발생시 서버에서 해당 페이지에 맞는 개수만큼만 가져온다.
*/
            	$.ajax({
		    url: "http://localhost:10000/articles",
		    dataType: 'json',
		    data: {
			 page : paging_1.page(),
			 pageCount : paging_1.options.pageCount,
			 screenCount : paging_1.options.screenCount
		    },
		    success: function(response) {
/**
가져온 데이터로 테이블 데이터를 바꾸고 
페이지계산을 다시한다
*/
			table_1.update(response.articles);
			table_1.resize();
			paging_1.reload(response.totalCnt);
		    },
		    error : function(response,txt){
			console.log(response);
			console.log(txt);
		    }
		});
            }
        },
        tpl: {
            pages: $("#tpl_pages").html()
        }
    });
});
```

**Comment by seogi1004** [comment]
@ParkMinKyu ajax 호출하는 부분을 보니 전체 데이터가 아니라 페이징된 데이터이므로 reload 메소드를 사용하면 안됩니다.

reload 메소드는 페이징 된 데이터 개수가 아니라 전체 데이터 개수가 변경되었을 때만 호출해야 합니다!

**Comment by ParkMinKyu** [comment]
네 그부분은 알고 있는데 
어쨌든 사용중에 게시물이 추가되거나 삭제될경우 총 게시물 수가 변경되서
 페이지를 다시계산해야 하는데
그때는 어쩔수 없이 reload()를 호출해야 하지 않나요?
 이때 reload() -> page() 가 계속 일어나서요.
 paging_1.reload(response.totalCnt); 이부분이 총게시물 수를 페이지에 리로드 한부분인데
저상태로 적용을 하면 계속 page() 이벤트가 무한 호출되서

```javascript
if( 현재 총 게시물수  != response.totalCnt){
 paging_1.reload(response.totalCnt);
paging_1.page(page);
}
```
이런식으로도 해봤는데
서버에서 불필요한 요청이 두번씩 일어나서 다른방법이 없을까 생각해봤는데
서버에서 페이징처리를 해서 html로 그리는거 뿐이 생각이 안나네요.^^;;

**Comment by seogi1004** [comment]
일단 reload를 하면 page 이벤트가 발생합니다.
totalCnt 가져오는 ajax 콜과 페이지 데이터 리스트를 가져오는 ajax 콜을 나눠야할 것 같네요.

**Comment by ParkMinKyu** [comment]
네 일단 나눠서 적용해보겠습니다~
답변 감사합니다.
