### ISSUE TITLE
datepicker의 reload 구현에 대한 문의

### ISSUE THREAD

**Issue by egaoneko** [juijs/jui#418]
다른 datepicker의 최소, 최대 날짜를 설정하는 부분을 적용해보고 싶은데 어떤 방식으로 적용해야할지 잘 떠오르지가 않네요.

datepicker의 API에 있는 setOption과 event의 select를 사용해서 구현하는 방식으로 하면 될 것 같은데, setOption을 해도 해당 날짜가 옵션에 적용되지 않는 문제와 reload()함수의 구현이 어렵습니다. reload()의 경우, page를 구현하는 방식과 비슷할 것 같아서 해봤는데 어렵네요.

```javscript
datepicker6 = datepicker("#datepicker6", {
            titleFormat: "yyyy MM",
            format: "yyyy/MM/dd",
            event: {
                select: function(date, e) {
                    alert(date);
                    datepicker7.setOption('minDate', new Date(date););
                    datepicker7.reload();
                }
            }
        });

        datepicker7 = datepicker("#datepicker7", {
            titleFormat: "yyyy MM",
            format: "yyyy/MM/dd",
            event: {
                select: function(date, e) {
                    alert(date);
                    datepicker6.setOption('maxDate', new Date(date));
                    datepicker6.reload();
                }
            }
        });
```

**Comment by easylogic** [comment]
@egaoneko  이슈 주셔서 감사합니다. 

아직 문서화가 안된  부분이 있는데요.. 

ui 최신 버전을 받으시면 

datepicker 에 minDate, maxDate 옵션이 있습니다.  

new Date() 객체로 설정하시면 

그것에 맞게  prev, next 가 적용이 되게 되어 있습니다. 

참고하세요.  

문서에 추가해놓겠습니다.

**Comment by egaoneko** [comment]
@easylogic 답변주셔서 감사합니다.
제가 설명을 잘 못 한것 같네요. 그 minDate와 maxDate를 활용해서 두 datepicker를 연동하고 싶습니다.
예를 들면 from date와 to date를 입력받는 경우, from date를 설정하면 to date에 minDate로 설정할 수 있으면 해서요.

**Comment by seogi1004** [comment]
@egaoneko options 프로퍼티는 참조 유지가 될텐데, 이상하네요.
업무가 끝나면 저녁쯤에 확인 한번 해보겠습니다.

**Comment by easylogic** [comment]
@egaoneko 

datepicker 소스를 다시 봤는데요. 

minDate, maxDate 는 현재 cache 되어서 다른 변수에 있습니다. 

그래서 외부에서 options 를 설정하더라도 적용이 되지 않네요.. 

reload 하실 때 아래 구분으로 다시 캐쉬를 설정하셔야할 것 같습니다. 

```javascript
            minDate = (_.typeCheck("date", opts.minDate)) ? opts.minDate : null;
            maxDate = (_.typeCheck("date", opts.maxDate)) ? opts.maxDate : null;
```

**Comment by easylogic** [comment]
참고로 reload 하실 때 아래와 같이 실행하시면 해당 달력으로 화면이 바뀝니다. 

```javascript
this.select() or this.select(minDate) ; 
```

**Comment by egaoneko** [comment]
@easylogic 답변해주신걸 바탕으로 만들어보겠습니다~
