### ISSUE TITLE
jui chart width 조정

### ISSUE THREAD

**Issue by joAhra** [juijs/jui#432]
jui column chart를 사용하고 있는데, 통계화면에서 날짜검색 시에  x축이 늘어나게 되면  x축의 날짜들이 겹쳐서 보이는 현상이 나타납니다. x축 데이터가 많을 경우 chart에 동적으로 스크롤이 생성되는 방법은 없을까요? chart의 witdh 를 조정하는 방법이 있다면 그 방법좀 알려주세요.

**Comment by easylogic** [comment]
문의 주셔서 감사합니다. 

scoll 형태로 쓸 수 있는 위젯이 있습니다. 

http://chartplay.jui.io/?p=candlestick_scroll 

이쪽을 보시면 코드를 확인 하실 수 있습니다. 

http://chartplay.jui.io/?p=mixed3_axis_3

이쪽 소스는 scroll 과 비슷한 개념인데  작은 차트가 나와서 영역을 지정하면 그 해당영역만 보여주는 개념입니다. 


한번 보시고 안되는 부분 있으면 다시 문의주세요.
