### ISSUE TITLE
jui datepicker 연 단위 이동

### ISSUE THREAD

**Issue by joAhra** [juijs/jui#434]
datepicker를 사용하고 있는데 월 단위 이동만 가능하고 연 단위 이동을 찾을수가 없어서 문의 드립니다.
연 단위로 이동하는 화살표를 추가하여 기능을 구현할 방법 없을까요??

**Comment by easylogic** [comment]
http://uiplay.jui.io/?p=datepicker_3  

여기 보시면 type 별로  구성을 따로 하실 수 있습니다. 

일단은 각 타입별로 있는지라 3가지 기능이 다 같이 연동된 것은 없습니다. 

월단위로 보고 계신 부분에서  년을 선택하는 버튼을 두고  연단위 datepicker 를 같이 표시 해주셔야 할 것 같아요. 

어떤식으로 쓰시는지 알려주시면 최대한 비슷한 예제를 만들어보겠습니다.

**Comment by joAhra** [comment]
type이 연 단위가 아닌 Daily date picker 상에서  < > 클릭 시 이전달/다음달로 이동하듯이  << >> 버튼이 추가되어 연 단위로 이동하는 기능이 필요합니다.  예를 들어 2016.07월 달력에서 << 클릭 시 2015.07월로  이동하면 됩니다.

**Comment by easylogic** [comment]
현재는 없는 기능이라 관련 기능 검토 해보겠습니다. 최대한 빠르게 적용해서 알려드리겠습니다.

**Comment by easylogic** [comment]
@joAhra  혹시 datepicker 사용하실 때  template 코드 좀 알려주실 수 있나요?

**Comment by easylogic** [comment]
@joAhra 

관련된 코드  https://github.com/juijs/jui/pull/435 여기에 PR 을 날렸습니다. 

배포되면 알드리겠습니다.

**Comment by joAhra** [comment]
네 감사합니다 ~~ 최대한 빨리 부탁드릴게요
