### ISSUE TITLE
아코디언 UI 오류 개선

### ISSUE THREAD

**Issue by search5** [juijs/jui#438]
기존 아코디언 샘플을 살펴보면, 1개의 div.content가 다른 아코디언 탭을 클릭할때마다 div.content를 재활용하도록 설계되어 있습니다.

이 경우의 문제를 해결하기 위해서 서버로부터 div.content를 채워줄 데이터를 가져와서 넣어주는 방법이 유일해보입니다.

이 문제의 오류를 내부 프로젝트에 아코디언을 사용하려다 보니 발견했습니다.

**Comment by easylogic** [comment]
@search5  샘플을 좀 수정해야겠습니다. 

의견 감사합니다.

**Comment by search5** [comment]
신속한 답변 감사드립니다.

(ps, 그런데 저는 이미 아코디언 소스 코드를 수정했습니다..)

**Comment by easylogic** [comment]
가만 보니 이미 쓰고 있던 패턴이 있어서  그 패턴을 바꿔버리면 쓰고 있던 분들이 업데이트 할 때 UI 가 완전히 바뀌는거라 데이타가 안나올 수가 있습니다. 

그래서 아래와 같은 옵션을 추가 해서 @search5 님이 하신 것을 적용 할려고 합니다. 
```javascript 
{
    multipanel : true 
}

```

어떻게 생각하시나요?

**Comment by search5** [comment]
저는 괜찮은 방법 같습니다.

**Comment by easylogic** [comment]
일단 코드 merge 하고  수정해서 다시 올릴게요.

**Comment by easylogic** [comment]
@search5 개선된 코드 develop 브랜치에 올려놨습니다. 

Sample 에 보시면  accordion.html 이 있는데요. 

여기에  multipanel 관련된 샘플도 추가해놨습니다.   

패널을 멀티로 구성할 수 있어서 좋네요. ^^

**Comment by search5** [comment]
@easylogic 빠른 응답과 개선 감사합니다. 사용하다 종종 기능 개선이나 오류 있으면 꾸준히 투척과 여력이 되면 지금처럼 관련 코드 넣겠습니다. 고맙습니다.

**Comment by search5** [comment]
@easylogic 그리고 제가 투척한 이슈들을 모두 반영해주셔서.. 모두 닫아주셔도 될것 같습니다..

**Comment by easylogic** [comment]
@search5 언제든지 환영합니다. ^^ 많은 관심 부탁드립니다. 감사합니다.
