### ISSUE TITLE
아코디언 샘플 코드 변경 요청

### ISSUE THREAD

**Issue by search5** [juijs/jui#440]
아코디언 탭의 타이틀에 표시되는 삼각형 이미지가 반대로 되어 있는 것 같습니다. 샘플이 2개인데, Default쪽에만 맞춰서 보냅니다.

```javascript
open: function(index, e) {
    $(this.root).find("i").attr("class", "icon-arrow1");
    $(e.target).find("i").attr("class", "icon-arrow3");
},
fold: function(index, e) {
    $(e.target).find("i").attr("class", "icon-arrow1");
}
```
html:
&lt;div id="accordion_1" class="accordion"&gt;
    &lt;div class="title active"&gt;
        Group Item #1 &lt;i class="icon-arrow3"&gt;&lt;/i&gt;
    &lt;/div&gt;
    &lt;div class="content"&gt;
        The style components provide various options in addition to the basic functionality.
        In addition, script components can be added, which facilitate the development of more diverse UI components.
    &lt;/div&gt;
    &lt;div class="title"&gt;
        Group Item #2 &lt;i class="icon-arrow1"&gt;&lt;/i&gt;
    &lt;/div&gt;
    &lt;div class="title"&gt;
        Group Item #3 &lt;i class="icon-arrow1"&gt;&lt;/i&gt;
    &lt;/div&gt;
&lt;/div&gt;

**Comment by easylogic** [comment]
샘플 수정하였습니다.  감사합니다.

**Comment by easylogic** [comment]
http://uiplay.jui.io/?p=accordion_3 여기 참고 하세요
