### ISSUE TITLE
아코디언 추가 기능 개선 요청

### ISSUE THREAD

**Issue by search5** [juijs/jui#441]
아코디언 오류를 발견하면서 아쉬웠던 점을 추가 기능 개선으로 요청드립니다.

지금 아코디언에서 발생하는 이벤트는 open과 fold만 있는데, init 이벤트도 발생했으면 좋겠습니다.

사실 init 이벤트가 발생했다면 추가 이슈로 처리하지 않고 프로그래밍으로 어떻게든 해결하려고 했었을것 같습니다.

**Comment by easylogic** [comment]
#438 이슈에서 수정되어서 닫습니다.
