### ISSUE TITLE
JUI 컴포넌트 조회하면에 폼 화면 내용 수정 필요합니다.

### ISSUE THREAD

**Issue by search5** [juijs/jui#447]
JUI.io에서 접속할 수 있는 컴포넌트 조회화면에서 다음 URL 맨 마지막에 있는 소스코드 화면 개선이 필요합니다.

http://uiplay.jui.io/?p=forms

수정 부탁드립니다.

ps. 아코디언 사용시 멀티 패널이 아닌 사용례도 자세히 명시되었으면 좋겠습니다.

**Comment by easylogic** [comment]
http://uiplay.jui.io/?p=forms  페이지 수정되었습니다.

**Comment by search5** [comment]
@easylogic 확인했습니다. pr은 안보내고 계속 요청만 드리고 있네요. 고맙습니다 :)

**Comment by easylogic** [comment]
@search5 
이렇게 이슈남겨주시는 것만으로도 좋습니다. 
 jui.io 쪽은 테스트 페이지 구성하는게 애매해서 그냥 이슈로 남겨주시는게 더 나을 것 같습니다. 
감사합니다.

**Comment by search5** [comment]
@easylogic 네, 지금처럼 그냥 열심히 이슈 남길게요 :) 요 얼마간 jui에 열심히 이슈 제기하고 있어서 왠지 죄송한 마음이 가득합니다.
