### ISSUE TITLE
여쭤볼만한 곳이 없어서 여기에 글을 올립니다. 한번 봐주세요..

### ISSUE THREAD

**Issue by yujinhee** [juijs/jui#450]
이제 프로그래머에 입문하는 단계라 어처구니없는 실수일 것 같은데 몇날 몇일을 검색해 봐도 답이 않나와 이렇게 글을 쓰게 되었습니다..
jui를 이용해보려고 샘플컴포넌트들을 작동시켜보는데 작동이 되는 것들이 있는 반면 잘 작동하지 않는 것들이 있어 질문드립니다.

소스는 http://uiplay.jui.io/ 에서 제공하는 소스를 붙여넣어 작동을 시켰고 jui jar파일은 http://jui.io/ 상단에서 전부 download하였습니다.
작동이 잘 되는 컴포넌트들도 있어서 경로의 문제는 아닌거같은데 어떤 문제인지 알려주시면 감사하겠습니다...ㅜ

[질문]
accordion중 multipanel속성을 사용하려고하는데 콘솔창에 아래와 같은 에러가 뜨길래  jui의 api에서 multipanel을 검색해보았으나 결과가 없었습니다....
실행 결과는 panel은 각 accordion란에 각각 들어가있으나 접히고 펼치는 기능이 안됩니다..
(multipanel속성을 사용하지 않는  accordion_2는 icon이 나오지 않지만 작동은 합니다.)
아래 콘솔창에 뜨는 에러메시지와 jsp전문을 올려드립니다. 번거로우시겠지만 확인 부탁드려요~
아니면 저같은 초보가 jui를 이용하면서 에러 발생 시 도움이 될만한 사이트가 있다면 알려주시면 감사하겠습니다.
이것 말고 grid에 scroll기능을 넣으면 일그러진다던가 jui에서 제공하는 icon이 안나온다던가  ui.plitter를 로드할수 없는 등의 에러가 발생해서 해결해보고 싶습니다...

[콘솔]
Uncaught Error: JUI_CRITICAL_ERR: 'multipanel' is not an option
    at Object.defineOptions (core.min.js:1)
    at Object.createUIObject (core.min.js:1)
    at HTMLDivElement.<anonymous> (core.min.js:3)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at core.min.js:3
    at VM44 NewFile6.jsp:38
    at HTMLDocument.<anonymous> (core.min.js:1)
    at Object.resolveWith (core.min.js:1)
    at Object.ready (core.min.js:1)
Failed to load resource: the server responded with a status of 404 (Not Found)   icomoon.woff
Failed to load resource: the server responded with a status of 404 (Not Found)   icomoon.ttf 
Failed to load resource: the server responded with a status of 404 (Not Found)   http://localhost:8080/favicon.ico 
(css나 js를 가져올 때 필요한 항목을 제가 빼먹은걸까요??..)

[ jsp소스 ]
&lt;%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%&gt;
&lt;!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"&gt;
&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv="Content-Type" content="text/html; charset=EUC-KR"&gt;

&lt;link rel="stylesheet" href="/jui/dist/ui.min.css" /&gt;
&lt;link rel="stylesheet" href="/jui/dist/ui-jennifer.min.css" /&gt;

&lt;link rel="stylesheet" href="/jui/jui-grid-master/dist/grid.min.css" /&gt;
&lt;link rel="stylesheet" href="/jui/jui-grid-master/dist/grid-jennifer.min.css" /&gt;

&lt;!-- &lt;link rel="stylesheet" href="/jui/jquery-3.1.1.min.js" /&gt; --&gt;
&lt;script src="/jui/jquery.min.js"&gt;&lt;/script&gt;

&lt;script src="/jui/jui-core-master/dist/core.min.js"&gt;&lt;/script&gt;
&lt;script src="/jui/dist/ui.min.js"&gt;&lt;/script&gt;
&lt;script src="/jui/jui-grid-master/dist/grid.min.js"&gt;&lt;/script&gt;
&lt;script src="/jui/jui-chart-master/dist/chart.min.js"&gt;&lt;/script&gt;

&lt;script type="text/javascript"&gt;

/*  */
jui.ready([ "ui.accordion" ], function(accordion) {
    accordion_2 = accordion("#accordion_2", {
        event: {
            open: function(index, e) {
                $(this.root).find("i").attr("class", "icon-arrow1");
                $(e.target).find("i").attr("class", "icon-arrow3");
            }
        },
        index: 0,
        autoFold: true
    });
});
/*//// */
 jui.ready([ "ui.accordion" ], function(accordion) {
    accordion_3 = accordion("#accordion_3", {
		multipanel : true,
        event: {
			init : function () {
				console.log('accordian initialized.');
			},
            open: function(index, e) {
                $(this.root).find("i").attr("class", "icon-arrow1");
                $(e.target).find("i").attr("class", "icon-arrow3");
            },
			fold: function(index, e) {
				$(e.target).find("i").attr("class", "icon-arrow1");
			}
        },
        index: 0,
        autoFold: true
    });
});
&lt;/script&gt;

&lt;title&gt;Insert title here&lt;/title&gt;
&lt;/head&gt;
&lt;body class='jui' &gt;
&lt;!-- ////////////// --&gt;
&lt;div id="accordion_2" class="accordion simple"&gt;
    &lt;div class="title active"&gt;
        Group Item #1 &lt;i class="icon-arrow3"&gt;&lt;/i&gt;
    &lt;/div&gt;
    &lt;div class="content"&gt;
        The style components provide variossssus options in addition to the basic functionality.
        In addition, script components can be added, which facilitate the development of more diverse UI components.
    &lt;/div&gt;
    &lt;div class="title"&gt;
        Group Item #2 &lt;i class="icon-arrow1"&gt;&lt;/i&gt;
    &lt;/div&gt;
    &lt;div class="title"&gt;
        Group Item #3 &lt;i class="icon-arrow1"&gt;&lt;/i&gt;
    &lt;/div&gt;
&lt;/div&gt;
&lt;br&gt;
&lt;!-- /////// --&gt;
&lt;div id="accordion_3" class="accordion simple"&gt;
	&lt;div class="title active"&gt;
		Group Item #1 &lt;i class="icon-arrow3"&gt;&lt;/i&gt;
	&lt;/div&gt;
	&lt;div class="content"&gt;
		First Accordion
	&lt;/div&gt;
	&lt;div class="title"&gt;
		Group Item #2 &lt;i class="icon-arrow1"&gt;&lt;/i&gt;
	&lt;/div&gt;
	&lt;div class="content"&gt;
		Second Accordion
	&lt;/div&gt;
	&lt;div class="title"&gt;
		Group Item #3 &lt;i class="icon-arrow1"&gt;&lt;/i&gt;
	&lt;/div&gt;
	&lt;div class="content"&gt;
		Three Accordion
	&lt;/div&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by seogi1004** [comment]
일단 master 브랜치 말고 develop 브랜치로 받아서 테스트해보세요!

**Comment by yujinhee** [comment]
develop브랜치로 받아도 안되서 개발자창이용해서 각 예제에서 사용되는 js 내용을 긁어다 쓰니까 되네요~ㅎㅎ 해결됬습니다~^^

**Comment by easylogic** [comment]
@yujinhee 다행입니다. 하시다가 안되시는 부분 있으면 언제든지 말씀해주세요.
