### ISSUE TITLE
firefox legend bug

### ISSUE THREAD

**Issue by crucifyer** [juijs/jui#453]
firefox 에서 legend 가 겹칩니다.
첨부는 html 입니다.

[test.txt](https://github.com/juijs/jui/files/1003455/test.txt)

**Comment by easylogic** [comment]
확인 하고 말씀드릴게요.

**Comment by easylogic** [comment]
@crucifyer  버그 확인 했습니다.  jui-core 쪽에 text size 구하는 쪽에서 파폭에서 정상적으로 동작하지 않는 버그가 있네요. 

수정하고 말씀드릴게요.

**Comment by easylogic** [comment]
@crucifyer 

https://github.com/juijs/jui-core/tree/develop/dist  에서 

core.js , core.min.js  다시 받아서 패치해주세요.

**Comment by crucifyer** [comment]
해결되었네요. 감사합니다.^^
