### ISSUE TITLE
datepicker와 input text상자 사용시 문제점...

### ISSUE THREAD

**Issue by Huntak** [juijs/jui#454]
현재는 datepicker에서 날짜를 선택해야만 input text 상자에 날짜가 들어가도록 해두었는데요
처음 load시에 input text 상자에 먼저 넣어 두고 싶은데 구현중에 어려움이 있습니다....
아래 처럼 소스를 구현하였습니다. 참고 하시고 답변 부탁드립니다..

```javascript
datepicker_2 = datepicker("#datepicker_2", {
	        titleFormat: "yyyy. MM. ",
	        format: "yyyy-MM-dd",
	        event: {
	        	select: function(date, e) {
	                //alert(date);
	                //console.log(e);
	                $("#dateTo").val(date);
	                $('#datepicker_2').hide(300);
	            },
	            prev: function(e) {
	                //alert("prev");
	            },
	            next: function(e) {
	                //alert("next");
	            }
	        },
	        tpl: {
	            date: $("#tpl_date").html()
	        }
	    });

	$("#datepicker_2").hide();
	$("#datepicker_2").css("left", $("#dateTo").offset().left);
```
```html
<script id="tpl_date" type="text/template">
    <td><!= date !></td>
</script>


<input type="text" id="dateTo" onclick="$('#datepicker_2').show(300);">
<div id="datepicker_2" class="datepicker" style="position: fixed;z-index: 1;display: block;">
	<div class="head">
		<div class="prev"><i class="icon-chevron-left"></i></div>
		<div class="title"></div>
		<div class="next"><i class="icon-chevron-right"></i></div>
	</div>
	<table class="body">
		<tr>
			<th>SU</th><th>MO</th><th>TU</th><th>WE</th><th>TH</th><th>FR</th><th>SA</th>
		</tr>
	</table>
</div>
```

**Comment by Huntak** [comment]
html 소스는 이상하게 올라가네요...

<input type="text" id="dateTo" onclick="$('#datepicker_2').show(300);">
						<div id="datepicker_2" class="datepicker" style="position: fixed;z-index: 1;display: block;">
						    <div class="head">
						        <div class="prev"><i class="icon-chevron-left"></i></div>
						        <div class="title"></div>
						        <div class="next"><i class="icon-chevron-right"></i></div>
						    </div>
						    <table class="body">
						        <tr>
						            <th>SU</th><th>MO</th><th>TU</th><th>WE</th><th>TH</th><th>FR</th><th>SA</th>
						        </tr>
						    </table>
						</div>

**Comment by easylogic** [comment]
@Huntak 

어떤 어려움이 있으신가요?  

최초 input 에 date 설정하는게 문제인가요?

**Comment by Huntak** [comment]
네네 최초에 input 상자에 날짜를 넣는게 문제입니다!

**Comment by easylogic** [comment]
기존에 저장해놓으신 date 를   $("#dateTo").val(date);   먼저 실행하는 구문은 없으신가요?

**Comment by Huntak** [comment]
아 기존에 저장을 해둘수 가 있나요 ?
date를 따로 저장해 두지않았습니다...
현재 날짜로 알아서 저장이 된것같아요 ~~

**Comment by easylogic** [comment]
@Huntak  

지금 하시고 싶으신게   input 박스에 있는 값으로  show 할 때 동일한 값으로 열고 싶으신건가요?

**Comment by Huntak** [comment]
음.... 아무래도 의사 전달이 잘 되지 않은것 같네요
select를 해야지만 선택한 날짜가 input 박스에 들어가는데
선택하기 전부터 input 박스에 날짜가 입력이 되있도록 하려고 합니다 ~~

**Comment by easylogic** [comment]
그런 용도면  html 로드 될 때 

```javascript
datepicker_2.select()  
```

이렇게 한번 실행주세요. 

그러면 정의하신 select 이벤트가 실행되실 꺼에요.

**Comment by Huntak** [comment]
이건 오늘 날짜를 datepicker에서 선택이 되어있도록 설정하는 메소드 아닌가요 ..... ?
저는 input 박스에 html 로드시에 datepicker에서 선택이 되어있는 날짜를 input 박스에 넣고 싶은건데
이렇게 하는게 맞나요...?
아니면 제가 이해가 잘 안된 부분인가요...?

**Comment by easylogic** [comment]
select(date) 이렇게 날짜를 넣어줄 수도 있습니다.  

원하시는 날짜를 넣어주시면 될 것 같아요.   

date 가 안들어가면 기본적으로 오늘날짜가 됩니다. 

https://github.com/juijs/jui/blob/develop/sample/datepicker.html  

여기를 참고하시면 좀 더 도움이 되실 것 같아요.

**Comment by Huntak** [comment]
오......사이트 보고 해결이 되었네요 ~~
매번 귀찮게하네요....
매번 정말 감사드립니다 ^^

**Comment by easylogic** [comment]
해결되셔서 다행이네요 ^^ 언제든지 질문은 환영입니다 ^^
