### ISSUE TITLE
return2 아이콘 오류 & Multi Selection for Select Box 사용시 SelectBox가 정의 되지 않는 오류

### ISSUE THREAD

**Issue by Huntak** [juijs/jui#457]
return2 아이콘이 정상적으로 출력되지 않습니다.

그리고 아래소스와 같이 사용하여본 결과 Uncaught TypeError: SelectBox is not a function 에러 메세지를 띄웁니다. 왜이럴까요....?

아니면 다른 방식으로 combo box에 input checkbox를 넣어서 여러개를 체크할 수 있게 만드려했는데
combo box에서 값을 선택하면 combo box 창이 닫혀버리네요... 창이 열려있을 때 checkbox 영역을 클릭했을 시에는 combo box 창이 닫히지 않도록 설정할 수 있을까요 ?
미리 설정해둔 메소드라서 event.stopPropagation(), event.preventDefault () 도 않먹네요...
혹시 다른 방법이 있을까요 ?

```javascript
jui.ready([ "ui.select" ], function(SelectBox) {
		var items = [
			{ value : '전체', html : '<strong>전체</strong>' } ,
			{ type : 'divider' },
			{ value : '성공', text : '성공' } ,
			{ value : '실패', text : '실패' } 
		];

		window.themeListMulti  = SelectBox('.theme-list-multi', {
			items : items,
			multi : true,
			event : {
				change : function (value) {
					console.log(value);
				}
			}
		});
	});
```

```html
<div class="theme-list-multi"></div>
```

**Comment by easylogic** [comment]
지금 쓰시는 jui 버전이 어떻게 되시나요?

**Comment by Huntak** [comment]
jui는 2.0.2
grid는 2.0.3
core는 2.0.5
chart는 2.0.5 사용중이에요 !

**Comment by easylogic** [comment]
https://github.com/juijs/jui/releases/tag/v2.0.3

2.0.3 쓰셔야 select 를 쓰실 수 있어요

**Comment by Huntak** [comment]
아 다운로드 받아서 다시하니 잘 돌아가네요 ^^
감사합니다 ~~~

**Comment by easylogic** [comment]
다행이네요. ^^

**Comment by easylogic** [comment]
@Huntak  

혹시 하나만 알려주실 수 있으신가요?  jui 를 어떤 프로젝트에 쓰시나요? 

저희가 너무 레퍼런스가 없어서  다들 어디에 쓰시는지를 잘 몰라요.. 

알면 좀 더 디테일 하게 지원할 수도 있을 것 같은데.  

아직은 갈길이 머네요.

**Comment by Huntak** [comment]
현재 회사내 솔루션 개발에서 사용하고 있어요 ^^
아직은 초기단계라서 어떤걸 만드는지 자세하게는 말씀드리기가 어렵네요...
항상 도움을 주셔서 감사합니다 ~~
