### ISSUE TITLE
bower 패키지 혼동

### ISSUE THREAD

**Issue by donamk** [juijs/jui#460]
bower에서 jui 설치시에 좀 혼동이 옵니다.

bower package search에서 jui를 찾으면
jui랑 jui@1.1.0이 있는데 깃 리포를 타고 가보면

jui@1.1.0은 최근에 업데이트 된 내용이 보이고
jui는seogi1004/jui 리포로 이동하고 작년 2월 커밋이 가장 최근으로 나옵니다.

jui@1.1.0이 owner도 jui-core, grid, chart와 동일해서  
jui 대신 jui@1.1.0을 설치해야 하는건가 싶어집니다.

별 문제는 아니지만 정리가 조금 필요한듯 싶습니다.

**Comment by easylogic** [comment]
@donamk  

안녕하세요. jui 에 관심 가져주셔서 감사합니다. 

현재 jui 1.x 버전때는 사용하고 있지 않습니다. 

2.x  대로 쓰시면 좋구여. 

2.x 대로 오면서 기존 구조가 완전히 바뀌어서  프로젝트가 총 4개로 나눠집니다. 

* jui-core    ui 코어 로직 
* jui            jui 관련된 클래스 
* jui-grid   grid 관련된 클래스 
* jui-chart   chart 관련된 클래스

**Comment by easylogic** [comment]
bower 에서 쓰실 때 

`
bower install jui-core 
bower install jui 
bower install jui-grid
bower install jui-chart 
`

이렇게 받으시면 됩니다.

**Comment by easylogic** [comment]
jui@1.1.0 은 지우고 싶네요 ^^;;;;;

**Comment by easylogic** [comment]
최대한 빨리 확인해서  진행사항 알려드릴게요.

**Comment by easylogic** [comment]
@donamk 

아무래도 bower 지원을 더 이상 못 할 것 같습니다. 

기존 패키지가 삭제가 되지 않아서 새로운 패키지를 등록하기가 애매한 상황이네요.

**Comment by donamk** [comment]
넵 알려주셔서 감사합니다. 상황이 그렇다고 하시니 뭐 어쩔수 없죠.
시간 소모만 하게 만든것 같아 죄송합니다ㅠㅠ

**Comment by easylogic** [comment]
아닙니다. 이렇게 라도 관심가져주셔서 감사합니다. ^^
