### ISSUE TITLE
데이터 종류가 매번 바뀔 때 문제점

### ISSUE THREAD

**Issue by lyt0324** [juijs/jui#463]
안녕하세요. 

JUI를 사용 중에 데이터 종류가 일정하지 않을 때 문제가 발생합니다.

ex) domain : [ 2000, 2001, 2002, 2003, 2004 ]
     data : [ 
             {a : 1, b : 2, c : 3} 
             {a : 2, c : 4} 
             {a : 3, b: 3, c : 5} 
             {b : 4, d: 1} 
             {d : 2, e: 3}
         ]

위 예제와 같이 데이터를 넣었을 때 중간에 비는 값들은 0으로 나와야 하는데 앞 뒤 데이터 평균값이 들어갑니다.

혹시 0으로 세팅하는 다른 방법이 있나요?

감사합니다.

**Comment by easylogic** [comment]
@lyt0324  혹시  샘플 구조를 다 올려주실 수 있으신가요? 

domain 이랑 data 가 정확히 매칭되어야 할때가 있습니다.  

차트 타입에 따라도 조금 달라질 수도 있습니다.

**Comment by lyt0324** [comment]
data : [
{A=1, B=16, C=4, D=2, E=1, F=1}
{A=1, B=17, C=5, D=2, E=1}
{A=1, B=17, C=2, D=1}
{A=1, B=17, C=2, D=2}
{A=1, B=17, C=1, D=2, E=1}
{A=1, B=17, C=1, D=3, E=1}
{A=1, B=18, C=1, D=1}
{A=1, B=18, C=1, D=6}
{B=17, C=1, D=2, E=1}
{A=1, B=17, C=1, D=2}
{B=18, C=1, D=2, E=4}
{A=1, B=4, C=1, D=2}
{B=2, C=1, D=2}
{B=10, C=1, D=7}
{B=12, C=1, D=1, E=1}
{B=12, C=1, D=2}
{A=1, B=12, D=2}
{A=1, B=11, C=1, D=2, E=1}
{A=1, B=11, C=1, D=2}
{A=1, B=17, C=1, D=2}
{B=18, C=4, D=2}
{A=1, B=12, C=1, D=2, E=1}
{A=1, B=15, C=2, D=2, E=1}
{A=1, B=18, C=2, D=2, E=1}
{B=16, E=4}
{B=18, C=1, D=2, E=1}
{A=1, B=14, C=1, D=2}
{C=1, D=2}
{A=1, B=18, C=1, D=1}
{B=17, C=1, D=2, E=1}
]
domain : [
{ 2000-01-01, ..... , 2000-01-30 }
]

둘 다 30개씩 데이터를 가지고 있는 상태입니다.

차트 타입은 line 쓰고 있습니다.

**Comment by easylogic** [comment]
@lyt0324 

주신 데이타로 코드를 다시 봤는데요. 

아무래도 비어있는 min 값을 채워주셔야 할 것 같습니다. 

값이 없을 때  min 값으로 대체하는 코드가 없네요. 

이건 정책상의 문제이긴 한데요.  

예전에 이런 이슈가 있었습니다.  같이 보시면 좋을 듯 합니다. 

https://github.com/juijs/jui-chart/issues/69

**Comment by lyt0324** [comment]
답변 감사합니다.
