### ISSUE TITLE
scatter(brush)와 legend filter(widget)을 같이 사용하면 문제가 발생합니다.

### ISSUE THREAD

**Issue by lyt0324** [juijs/jui#464]
안녕하세요. 

데이터의 양이 많아 'scatter' 기능을 사용한 Line 차트를 구현하려 하고 있습니다. 

그런데 밑의 소스로 세팅을 한 후 legend의 filter기능을 사용하면 scatter의 원은 남아있는 문제가 발생합니다.
```javascript
brush : [{
	type : "line",
        activeEvent : "mouseover",            // scatter와 이벤트 연동 X
	target : targetList
},{
       	type : "scatter",	
        symbol : "circle",
        size : 5,
       	target : targetList,
}],
        widget : [{
      	type : "title",
       	text : "Line Sample"
}, {
       	type : "legend",
       	filter : true                                     // scatter와 이벤트 연동 X
}]
```
또한 위의 내용과 비슷한 것으로 brush 속성 중 'activeEvent'를 사용할 때에도 scatter의 원의 opacity가 변하지 않습니다.

혹시 제가 잘못사용하고 있는 건지 아니면 'filter'와 'activeEvent'는 'scatter'와 같이 사용할 수 없는 상태인지 궁금합니다.

답변 부탁드립니다!

**Comment by easylogic** [comment]
안녕하세요. @lyt0324   

legend 속성 중에  brushSync : true 가 있습니다.    아래와 같이 설정해서 한번 해주세요. 

```javascript
{
    type : 'legend',
    filter : true, 
    brushSync : true,  // action 에 대해서 모든 brush 적용 
    brush : [0, 1]     // 0 번  line, 1 번 scatter  모두 적용 
}
```

**Comment by lyt0324** [comment]
주석까지 달아주시고 감사합니다. 

잘 됩니다 :)

**Comment by easylogic** [comment]
@lyt0324  

쓰시다가 불편한 점 있으시면 언제든지 여쭤봐주세요.  ^^

**Comment by lyt0324** [comment]
감사합니다!

**Comment by easylogic** [comment]
@lyt0324  혹시나 다음에도 차트 관련 이슈 남길일이 있으시면 

https://github.com/juijs/jui-chart 

쪽으로 남겨주시면 감사하겠습니다. 

juijs/jui  쪽은 순수하게 UI 쪽이라 ^^;;

**Comment by lyt0324** [comment]
넵 감사합니다^^
