### ISSUE TITLE
updateWidget 메소드관련

### ISSUE THREAD

**Issue by ruji704** [juijs/jui#465]
특정 연/월 변경시에 그래프의 title을 변경하도록
제공함수인 updateWidget을 사용하였으나 변경이 되질 않습니다.
사용법은 updateBrush와 마찬가지로

chartID.updateWidget(0,{type:"title",text:"title233",size:20});
실행후 되질않아
chartID.render(); //다시그리기
를 추가하였으나 변함은 없습니다.

사용법을 알고싶습니다.

**Comment by easylogic** [comment]
@ruji704 

답변이 늦어서 죄송합니다. 

혹시 전체 차트 렌더링 코드를 올려 주실 수 있나요? 

차트 생성 하실 때   

render : true  or false  

옵션을 주실 수 있는데 

사용패턴에 따라 렌더링 하는 방식이 좀 달라져서요.

**Comment by ruji704** [comment]
제가 소스를 보니깐 render에 true를 주지않으면 widget을 다시 못그리는것 같아서
true를 주니깐 잘되네요! 이렇게 사용하는게 맞을까요?


참고로 소스는
---전체소스코드

var chart = jui.include("chart.builder");
chart_L = chart("#chart_L", {
           width: "100%",
           height : "100%",
           padding : {
               top : 60,
               left : 65,
               right : 20,
               bottom : 40
           },
           axis : [
               {
                   y : {
                       type : "range",
                       domain : [0,100],
                       format : function(value) {
                       return value;
                       },
                       line : true,
                       step : 10

                   },
                   x : {
                       type : "block",
                       domain : "KPI_MONTH",
                       line : false
                   }
               }
           ],
           brush : [{
               type : "column",
               size : 15,
               target : [ "KPI_VAL" ],
               colors : ["#5698D4"]
           }],
           widget : [{type : "title", text : lastYear, size : 20},
                 {type : "title",text:"Kwh/vehicle", align : "start",orient
: "center", size : 20,dx:-55 }]

           ,style : {
            tooltipPointRadius : 0,
            //titleFontWeight: "bold",
            gridYAxisBorderWidth : 1,
               gridXAxisBorderWidth : 1,
               gridXFontSize : 12,
               gridYFontSize : 12
           }
       });




// 그래프 타이틀 지정
chart_L.updateWidget(0, {type :"title", text : "TEST", size : 20},true);
chart_L.render(true);

2017년 11월 15일 오후 1:52, jinho park <notifications@github.com>님이 작성:

**Comment by easylogic** [comment]
@ruji704 

네 맞습니다.  widget  은 순간 그려지는 개념이 아니라서  만약에 위짓 자체가 변경되는 것이면 전체를 다시 다 렌더링 하는게 맞습니다.
