### ISSUE TITLE
table, datepicker 함께 사용할 때 질문입니다.

### ISSUE THREAD

**Issue by luga3377** [juijs/jui#472]
데이터 검색용 화면을 만들고 있습니다.

table, combo, datepicker, popup 등등 여러가지를 가져다 쓰고 있습니다.

그런데 화면이 로드 될 때 테이블에 데이터 없을 때 빈 행이 나오도록 설정해 두었는데
빈 행이 나오질 않습니다.

여기서 datepicker 를 제외하면 제대로 나옵니다.

함께 사용할 수 없는 것인지 확인 부탁드립니다.

// 소스 참조
jui.ready([ "grid.table", "ui.window", "ui.datepicker", "util.dom", "ui.combo" ], function(table, win, datepicker, _, combo) {
                    // 테이블 셋팅
		    table_1 = table("#table_1", {
		        fields: arrFields,
		        data: [],
		        tpl: {
		            row: $("#tpl_row").html(),
		            none: $("#tpl_none").html(),
		        }
		    });

	    	// 작업일 셋팅
		    calWorkDt = datepicker("#calWorkDt", {
	            titleFormat: "yyyy/MM",
	            format: "yyyy/MM/dd",
	            event: {
	                select: function(date, e) {
	                    $("#calWorkDt_group").find("input").val(this.getFormat("yyyy/MM/dd"));
	                    $("#calWorkDt_group").find("a").click();
	                }
	            }
	        });

	        // 해당 메소드 호출시 select 이벤트가 발생함
	        calWorkDt.select(new Date());

	        $("#calWorkDt_group").find("a").on("click", function(e) {
	            var $r = $(calWorkDt.root);

	            if($r.css("display") == "none") {
	                $r.show();
	            } else {
	                $r.hide();
	            }
	        });
// 생략
}

감사합니다.

**Comment by seogi1004** [comment]
오잉 해결하셨어여??
