### ISSUE TITLE
도넛 브러쉬 개선 및 의견 공유

### ISSUE THREAD

**Issue by seogi1004** [juijs/jui#69]
참고 : http://www.anychart.com/products/anychart/docs/users-guide/Pie-Donut.html

**Comment by seogi1004** [comment]
http://dsgnblvd.com/envato/edge-animate-svg-donut-charts/01.1.single-bar/donut_charts.html

**Comment by seogi1004** [comment]
![590px_preview](https://cloud.githubusercontent.com/assets/1277117/5716142/09334d7a-9b2a-11e4-98aa-42c66dbbf0d4.jpg)

**Comment by easylogic** [comment]
도넛 path 의 stroke 만 가지고 그리도록 구성을 바꿈. 

활용도가 많아 질 듯.

**Comment by seogi1004** [comment]
이거 어떻게 되고 있음~ 빨리 해주셈!

**Comment by easylogic** [comment]
개발은 저 멀리 ~

**Comment by seogi1004** [comment]
님하~ 할껀하셔야합니다 ㅋㅋ

**Comment by seogi1004** [comment]
http://jsfiddle.net/lim831128/a5s8m/2/

3d 도넛 예제

**Comment by easylogic** [comment]
3d pie, donut 구현 했음 .

**Comment by easylogic** [comment]
아 ~ 3d pie, donut 너무 안 이쁨. 

디자인을 바꿔서 다시 만들어야할 듯

**Comment by seogi1004** [comment]
depth랑 angle이 적용안되지 않슴?

**Comment by easylogic** [comment]
기능은 있는데  그리드 형태가 아니라 브러쉬에서 구현한거라 그리드 형태로 맞춰야할듯 

grid3d 써서

**Comment by seogi1004** [comment]
저거 디자인대로 구현을 하긴해야할텐데...
장기적으로 봅시다.
